### ISSUE TITLE
Problem using a Monx store with HyperMoon created component

### ISSUE THREAD

**Issue by kokujin** [kbrsh/moon#100]
`````
var testComp = m('h1', { attrs: {} }, { shouldRender: false }, [m("#text", { shouldRender: true }, store.state.selectedTool)]); // <--- Does not get updated

Moon.component("foo-component", {
        render: function(m) {
            return testComp;
        }
    });
`````
Other components work well with the store. I have tried setting both "shouldRender" values to true, that did not work either.
Any idea what I am doing wrong?

**Comment by kbrsh** [comment]
So the `m` function returns a virtual DOM, with all of the information.

In this case, the text node has content with `store.state.selectedTool`. The virtual DOM loaded in the `testComp` variable has a virtual DOM with the value of the state at that point. To use a store with a component, you need to inject it into the instance by adding it in the options.

Also, it's generally a bad practice to use custom render functions for simple cases like this. If you use a template, Moon basically creates the same function after compiling it (the compiler makes up about 50% of Moon's source code).

I'd recommend you do something like this:

```js
Moon.component("foo-component", {
  template: "<h1>{{store.state.selectedTool}}</h1>",
  store: store
});
```

But if you really want a custom render function, you can use what you have above, just inject the store and make sure you return a new virtual DOM in the render function each time.

Once again, I'd recommend you use templates, as Moon's compiler is fairly smart and includes an optimizer. That's the main reason I have the `shouldRender` property, as the compiler can easily detect static nodes and mark `shouldRender` as `false`.

If you try going on the [compiler](http://moonjs.ga/docs/compiler.html) page, you'll see in the example at the bottom what Moon can generate from your HTML. Try using `{{mustache}}` templates and notice how `shouldRender` changes accordingly.

**Comment by kokujin** [comment]
Actually, I have a few complicated components I would like code, the reason why I needed a more comfortable way to construct, that being HyperMooon. 
I would be wrapping some widgets from a CSS framework also, and some of them are several lines long, they would just be to clumsy to write as string literals.

Thanks once again for your help.

**Comment by kbrsh** [comment]
Yup, I understand. You can use something like:

```js
Moon.component("foo-component", {
  render: function(m) {
    var store = this.get("store");
    return m('h1', { attrs: {} }, { shouldRender: false }, [m("#text", { shouldRender: true }, store.state.selectedTool)]);
  },
  store: store
});
```

In this version, every time the Monx state is updated, the `render` function will return a new instance of the virtual DOM (with the updated version of `store.state.selectedTool`.

Let me know if this works.

**Comment by kokujin** [comment]
@kbrsh , no luck. I even tried renaming the store just in case the render function was having problems with scope.

``````
 Moon.component("foo-component", {
        render: function(m) {
            var internalStore = this.get("store");
            M.util.log('store in foo : ', internalStore.state.projects);
            return m('h1', { attrs: {} }, { shouldRender: false }, [m("#text", { shouldRender: true }, internalStore.state.selectedProject)]);
        },
        store: store
    });
``````

Using a template not created with HyperMoon works though.

**Comment by kbrsh** [comment]
This seems like a bug in Monx. I'll look into it.

**Comment by kbrsh** [comment]
Actually, I don't think this is a bug. I tried reproducing it in a jsFiddle and was successful. Can you provide a reproduction of the issue?

Are you making sure `store` is in the scope and is the result of initializing Monx with `new Monx`? (The `new` keyword is important here).

**Comment by kokujin** [comment]
Yes I am, like this:
`````
$(function() {
    // HyperMonn
    const m = Moon.util.m;

    // Init Moon plugins
    Moon.use(Monx);

    const store = new Monx({.....
`````

Everything works except this component with the HyperMoon created template. The only thing that might have an influence is that I have at least 8 components in the same scope, all registered to the same store. I will try to create a fiddle as soon as possible.

**Comment by kokujin** [comment]
Here is a simplified example of what I'm trying to do. Its not in a fiddle or Plunkr though

`````
$(function() {
    // HyperMoon
    const m = Moon.util.m;

    // Init Moon plugins
    Moon.use(Monx);

    const store = new Monx({
        state: {
            tools: [],
            selectedTool: ['Spanner', 'Screwdriver']
        },
        actions: {
            updatetools: function(state, payload) {
                state.tools = payload;
            },
            selectTool: function(state, payload) {
                console.log(payload);

                state.selectedTool = payload;
            }
        }
    });

    // Project selector
    Moon.component("project-selector", {
        template: `<select m-on:change="switchTool">
            <option m-for="item in store.state.tools">{{item}}</option>
        </select>`,
        data: function() {
            return {
                tools: []
            }
        },
        methods: {
            switchTool: function(val) {
                var selectWidget = val.target;
                var t = selectWidget.options[selectWidget.selectedIndex].value;
                store.dispatch("selectTool", t);
            }
        },
        store: store
    });

    Moon.component("foo-component", {
        render: function(m) {
            var store = this.get("store");
            console.log(store.state.tools);
            console.log(store.state.selectedTool);
            return m('h1', { attrs: {} }, { shouldRender: false }, [m("#text", { shouldRender: true }, store.state.selectedTool)]);
        },
        store: store
    });

    const app = new Moon({
        el: "#app-moon"
    });

    // This happens after an AJAX call
    store.dispatch("updatetools", ['hammer', 'wrench']);
});

`````

I will create a fiddle if the problem is still not clear. Thanks

**Comment by kbrsh** [comment]
Have you tried it with a render function with:

```js
return m('h1', { attrs: {} }, { shouldRender: true }, [m("#text", { shouldRender: true }, store.state.selectedTool)]);
```

I changed the `h1`'s `shouldRender` to `true` so that Moon doesn't skip it.

**Comment by kokujin** [comment]
That was it, it works now. :)  I will test it with several other components again,
