### ISSUE TITLE
Defining templates in html and referencing ID

### ISSUE THREAD

**Issue by chasebank** [kbrsh/moon#102]
Similar to what can be done in Vue, is this possible?

```
Vue.component('greeter', {

    template: '#greeter',

    props: ['name'],
});
```

```
<template id="greeter">
    <div>Hello, {{ name }}!</div>
</template>
```

or 
```
<script type="text/x-template" id="greeter">
    <div>Hello, {{ name }}!</div>
</script>
```

**Comment by kbrsh** [comment]
This isn't possible, but can definitely add it. I wouldn't recommend doing so personally (I would say it is a bad practice), because it is better to associate all options of a component with it's template.

Or you could use single file components.
