### ISSUE TITLE
Moon bars demo broken for firefox.

### ISSUE THREAD

**Issue by BlueXiphoid** [kbrsh/moon#104]
*Chrome*
<img width="655" alt="screen shot 2017-08-26 at 20 44 25" src="https://user-images.githubusercontent.com/924615/29744174-bc1789a8-8a9f-11e7-9925-5edbc17a6144.png">

*Firefox 55.0.2*
<img width="583" alt="screen shot 2017-08-26 at 20 44 30" src="https://user-images.githubusercontent.com/924615/29744175-c7ec4a3e-8a9f-11e7-9954-48c74e742625.png">

No errors in console.

**Comment by kbrsh** [comment]
Huh. Can you please transfer this issues to the moon-bars repo? I think it might have to do with the visibility of the SVG. Can you verify the SVG element actually exists?

**Comment by BlueXiphoid** [comment]
Done.

https://github.com/kbrsh/moon-bars/issues/1

**Comment by kbrsh** [comment]
Awesome, closing in favor of the new issue.
