### ISSUE TITLE
list of other frameworks is missing Preact (3kb)

### ISSUE THREAD

**Issue by soenkekluth** [kbrsh/moon#105]
be fair and add Preact to the List - 
http://moonjs.ga/docs/overview.html

https://github.com/developit/preact

**Comment by abshammeri** [comment]
He's already fair.. and mention that in his [blog](https://hackernoon.com/introducing-moon-1d44a99635f0)

**Comment by kbrsh** [comment]
I'll add Preact, as it was definitely one of the main inspirations for Moon (as I stated in the article @abshammeri linked).

**Comment by soenkekluth** [comment]
:thumbsup:
