### ISSUE TITLE
Can't see typed in input#search with firefox 55.0.2

### ISSUE THREAD

**Issue by Erkajp** [kbrsh/moon#107]

**Comment by kbrsh** [comment]
It would be great if you could give a screenshot or a description of what is happening 😅

**Comment by Erkajp** [comment]
![test](https://user-images.githubusercontent.com/8047705/29755801-ab118b12-8bc7-11e7-90f4-ac36a3c9cccf.png) 
i has been type some text use firefox, text not not visible and the cursor minimize

**Comment by kbrsh** [comment]
Odd. I'll look into it, thanks!
