### ISSUE TITLE
Hooks are confusing / have insufficent documentation

### ISSUE THREAD

**Issue by Temeez** [kbrsh/moon#110]
```
el: "#app1",
data: {
  msg: "Hello Moon!",
},
hooks: {
  mounted: function() {
    console.log(this.msg)
  }
}
```
`> undefined`

I have some vuejs experience and since moon docs are so puny compared to vuejs docs I assumed that the above would work like it does in vuejs but nope. `this.set()` also seems to do nothing in `mounted`. 😕

**Comment by kbrsh** [comment]
Moon doesn't proxy data to the instance, you need to use `.get("msg")`.  If you can provide a reproduction of `.set` in `mounted` not working, it would be great.

**Comment by mememaestro** [comment]
Try to replace `this` to your Moon instance variable

**Comment by kbrsh** [comment]
@ctl That can work, but `this` is automatically bound to the instance for every function of an instance.

**Comment by Temeez** [comment]
@kbrsh whelp.. I seem to have missed `this.get()`, probably due to it being barely visible at the bottom of the **getting started** page.

Would be a good idea to put a **Getting Data** title with a simple example with `get()` somewhere above **Methods** title on that page.
