### ISSUE TITLE
Replacing Root Element with `template` Option

### ISSUE THREAD

**Issue by ctl** [kbrsh/moon#111]
What i expected:
` <div id="app"><MyComponent></MyComponent></div>`
What i got:
![image](https://user-images.githubusercontent.com/31369180/29779512-74761240-8c1b-11e7-9131-75e6309e26e8.png)
My code:
```
var Moon = require('moonjs');
var MyComponent = require('./components/index.moon');

new Moon({
	el: "#app",
	template: "<MyComponent></MyComponent>"
});
```
I found that `template:` eats  element ,but  not appending into this element . It's a bug or normal behaviour?

**Comment by kaasasolut** [comment]
Please create [a Fiddle](https://jsfiddle.net/) or similar so we can understand your issue better.

**Comment by ctl** [comment]
@kaasasolut Ok. [Here it is](http://requirebin.com/?gist=adf7555b3db1c74cf06d4c4b063d9642)

**Comment by kbrsh** [comment]
@ctl The `template` option _includes_ the parent node. This is documented behavior and is expected in Moon and Vue.
