### ISSUE TITLE
Multiple Moon init problem

### ISSUE THREAD

**Issue by kokujin** [kbrsh/moon#118]
I noticed that when I initialize moon on the BODY tag, it gets initialized multiple times and it sporadically causes problems.

Moon init in main.js

```js
 const app = new Moon({
      el: "#app-moon"
 });
```

In my index.html template

```html
<body id="app-moon">
```
I get this log in the console

```
======= Moon =======
======= Moon =======
XHR finished loading: GET "http://localhost:3030/products".
dispatchXhrRequest
xhrAdapter @ app.js:3766
dispatchRequest @ app.js:4425
Axios Object {data: Object, status: 200, statusText: "OK", headers: Object, config: Object…}
 ======= Moon =======
```

Any idea what I am doing wrong? Thanks

**Comment by kbrsh** [comment]
I'm going to need more details on the `index.html` template and your code. Can you provide a reproduction in a jsFiddle or something similar?

**Comment by kokujin** [comment]
I am closing this for now because I was having a hard time making the fiddle since it was complicated( Moon components, Monx and other things).

I could solve my problem though by using a different document ready detection approach.
`````
document.addEventListener("DOMContentLoaded", function(event) { 
  // Code
}); 
`````
