### ISSUE TITLE
I just found out that I had missed a lot of documentation

### ISSUE THREAD

**Issue by Temeez** [kbrsh/moon#119]
Because it's hiding behind /api/ and I never took a look at the main page urls after clicking "Getting Started" which takes the user to /docs/. 😠 

Any chance if combining them or at least putting links to the side navs?

**Comment by kbrsh** [comment]
Good idea! I'll add an "API" section to the side nav of the docs, and a "Documentation" section on the side nav of the API docs.

**Comment by sudomabider** [comment]
I'll slightly hijack this issue and just point out that there's a mistake in the doc at `api/configuration.html` where it says

```
Moon.config.keycodes({
  m: 77
});
```

should be `keyCodes` with an uppercase `C`.

_[slowly disappearing back into the dark...]_

**Comment by kbrsh** [comment]
Haha thank you! Will fix that as well. 😅
