### ISSUE TITLE
$children

### ISSUE THREAD

**Issue by karlseguin** [kbrsh/moon#123]
I was trying to build a tab component. Something similar to:
https://github.com/spatie/vue-tabs-component/tree/master/src/components

But the lack of a `this.$children` equivalent seems to make that impossible. I tried to define my `tabs` using an `m-insert` but then there's no way to pass props to children, which you need in order to set the 'active' prop reactively.

The containing "tabs" needs to loop through its children and set active = false except for on the currently active tab (which needs to be set to true of course)

**Comment by kbrsh** [comment]
@karlseguin Sorry for the late response.

I think I've found a way to overcome this. Inserts are stored in `instance.insert`. You can loop through the array of virtual DOM children, and access the component instance with:

```js
child.data.component;
```

Then you can run:

```js
child.data.component.set("active", false);
```

Putting it together:

```js
const insert = instance.insert;
for(let i = 0; i < insert.length; i++) {
  const child = insert[i];
  if(child.type === "ComponentName") {
    child.data.component.set("active", false);
  }
}
```

**Comment by kbrsh** [comment]
Components now have access to child elements through `children`. However, they don't have local state anymore so this component would be implemented differently anyway.
