### ISSUE TITLE
Template compiler doesn't handle whitespace correctly

### ISSUE THREAD

**Issue by ricardobeat** [kbrsh/moon#127]
Using the example straight from [moon-bars](https://kbrsh.github.io/moon-bars) page:

```javascript
Moon.use(MoonBars)
new Moon({
    el: "#app",
    template: html`<div>
        <p>hello from moon</p>
        <bars
            m-literal:data="[5, 7, 4, 3, 5]"
            m-literal:fill="['#7bddd3', '#079af9']"
            height="40"
            width="100">
        </bars>
    </div>`,
    data: {}
})
```

(note `html()` is a no-op returning the string - there just for syntax highlighting)

the compiler chokes on the whitespace between the opening `<bars` and it's attributes. 

<img width="492" alt="screen shot 2017-09-05 at 14 50 14" src="https://user-images.githubusercontent.com/97396/30061935-ab742078-9249-11e7-94bf-b08ec7bc1742.png">

**Comment by kbrsh** [comment]
This is a known issue, and will be fixed in v1.
