### ISSUE TITLE
One error in examples in  the doc

### ISSUE THREAD

**Issue by lukesomnus** [kbrsh/moon#128]
Hello, kbrsh. I found that in the docs:
```
const app1 = new Moon({
  el: "#app1",
  data: {
    msg: "Hello Moon!"
  }
});
```
the 'el' property in the option should be the 'root'.It happens in all examples. 
I read the source code in the gh-pages branch , and I found 
```
    Moon.prototype.mount = function(el) {
      // Get element from the DOM
      this.$el = typeof el === 'string' ? document.querySelector(el) : el;
      ........
    }
```
So I think it's because your docs is behind your master branch.

**Comment by kbrsh** [comment]
That's not a mistake in the docs. The `master` branch has the source for the current development of Moon v1 (which has a lot of breaking changes). To get v0.11.0, check out [this](https://github.com/kbrsh/moon/tree/6f782afe0010f04a05d8f5f871f843e83be13778) tag.
