### ISSUE TITLE
Rendering a single item from a former object/array

### ISSUE THREAD

**Issue by vkeusebio** [kbrsh/moon#131]
This is how I render a former array (*TIL that moon returns a single element array as a string*):
```html
<ul>
    <li m-if="typeof(pairs) === 'object'" m-for="pair in pairs">{{pair}}</li>
    <li m-if="typeof(pairs) === 'string'">{{pairs}}</li>
</ul>
```

Ugly, I know. Any suggestions?

**Comment by kbrsh** [comment]
Hmm. Moon shouldn't be returning an array with a single element as a string. Can you provide a jsFiddle reproducing this?

**Comment by kbrsh** [comment]
This isn't a problem with `.get`. It's because `.pop()` returns the removed item, and that is what is stored in `p`.

Try:

```js
let p = this.get('pairs').slice();
p.pop();
this.set('pairs', p);
```

**Comment by vkeusebio** [comment]
Oh, that did it. It appears that `this.get('pairs').pop()` also works.
