### ISSUE TITLE
Emit handler is function not array

### ISSUE THREAD

**Issue by LeviSchuck** [kbrsh/moon#132]
```js
   Moon.prototype.emit = function(eventName, customMeta) {
      // Setup metadata to pass to event
      var meta = customMeta || {};
      meta.type = eventName;
    
      // Get handlers and global handlers
      var handlers = this.$events[eventName];
      var globalHandlers = this.$events["*"];
    
      // Counter
      var i = 0;
    
      // Call all handlers for the event name
      if(handlers !== undefined) {
        for(i = 0; i < handlers.length; i++) {
          handlers[i](meta);
        }
      }
...
```
I get an exception on `handlers[i](meta);`, when inspecting, it seems handlers is being set to the following anonymous function, rather than an array of functions.

The anonymous function being `function(evt) { ...`

```js
      var addEventListeners = function(node, eventListeners) {
      var addHandler = function(type) {
        // Create handle function
        var handle = function(evt) {
          var handlers = handle.handlers;
          for(var i = 0; i < handlers.length; i++) {
            handlers[i](evt);
          }
        }
```

Changing the exception point to happened to resolve this for me.
```js
      // Call all handlers for the event name
      if(handlers !== undefined) {
        handlers(meta);
      }
```

PS. I had to edit stuff in node modules just to be able to see where in moon this was. It would be nice if `npm run dev` mode didn't use the minified moon JS.

**Comment by kbrsh** [comment]
This is actually a really common issue and is fixed in v1. There will be a _huge_ commit pushed soon that is literally a rewrite of Moon, shaving off 1kb and adding a ton of new features.

As for the development mode stuff, try using `require("moonjs/dist/moon.js");` to load the development version of Moon. I can try to add it in the template through a check for `NODE_ENV`.

**Comment by LeviSchuck** [comment]
I actually just hit the expected case where it is an array so my little fix is not wholesome 😢 

I'm having fun though! How soon is soon?

**Comment by kbrsh** [comment]
I am planning on releasing a beta version of v1 soon, to iron out some bugs. I've spent the last month or so rewriting Moon, and I actually finished today!

**Comment by LeviSchuck** [comment]
After throwing in a little hack, I've been able to continue on my way.
```js
    if(handlers !== undefined) {
        if(Array.isArray(handlers)) {
          for(i = 0; i < handlers.length; i++) {
            handlers[i](meta);
          }
        } else {
          handlers(meta);
        }
      }
```

I look forward to the beta!
I've been working on my own project for the last month and finally want to make something user facing (as opposed to admin) and phone friendly. In short, text-adventure games with text, pictures, and buttons, scriptable with a lisp as a service.
