### ISSUE TITLE
Can one send an Object from a parent into a Component?

### ISSUE THREAD

**Issue by avermeulen** [kbrsh/moon#136]
Is it possible to send an object reference (object literal) to a component instead of just a string or a number?

In the code sample below I can't send `parentObj` into the component. Well I can send it in but not access it attributes in the component template using `obj.msg`.

Is this approach not supported or am I doing it wrong?

```javascript
Moon.component('my-component', {
  props: ['content', 'obj'],
  // obj.msg will always be undefined
  template: "<p>Data from Parent: {{content}} Message from obj: {{obj.msg}} </p>"
});

const app2 = new Moon({
  el: "#app2",
  data: {
    parentObj: {
      msg : "Parent Data"
    },
    parentMsg : "Gogo!"
    
  }
});
```

```html
<div id="app2">
    <my-component content="{{parentMsg}}" obj="{{parentObj}}"></my-component>
```

You can see a running example of the code here: http://jsbin.com/pozihalewu/1

**Comment by kbrsh** [comment]
I was asked this question 3 times just yesterday. 😅 
Check out the API docs for `m-literal`.

```html
<my-component content="{{parentMsg}}" m-literal:obj="parentObj"></my-component>
```
