### ISSUE TITLE
Testing moon components and applications

### ISSUE THREAD

**Issue by kokujin** [kbrsh/moon#137]
@kbrsh, Is there a link to examples on how you prefer to test components and applications using MoonJs? Thanks

**Comment by emoticon** [comment]
@kokujin, you need to test your Moon application?

**Comment by kokujin** [comment]
@emoticon, do you have an example test harness using Karma?

**Comment by emoticon** [comment]
@kokujin you can find tutorials in internet
[This can help you](http://attackofzach.com/setting-up-a-project-using-karma-with-mocha-and-chai/) and [this](https://sean.is/writing/client-side-testing-with-mocha-and-karma/) and even [this](https://habrahabr.ru/company/rambler-co/blog/278503/)  (in russian)

**Comment by kbrsh** [comment]
@kokujin It's similar to how you would do it in Vue.

In Moon v0.11.0, the element of an instance can be accessed with `instance.$el`.
In Moon v1 (currently being developed on the `master` branch), you can access the element of an instance with `instance.root`.

**Comment by kokujin** [comment]
Thanks
