### ISSUE TITLE
(Monx?) Within m-props that use the store, children don't get updated independently

### ISSUE THREAD

**Issue by LeviSchuck** [kbrsh/moon#138]
I encountered a weird case. It seems that with some element nesting and conditions, re render calls are not being made.

In particular, when `store.state.choice` and `store.state.prompts` changes after `store.state.accepted` has changed once, re render does not occur:
```
      <c-button m-if="store.state.pendingAgree" m-on:click="agree" content="Agree"></c-button>
      <div m-if="store.state.accepted">
        <div class="normal-scene">
          <prompt m-literal:options="store.state.prompts" m-literal:choice="store.state.choice" m-on:choose="choose"></prompt>
        </div>
      </div>
```

But, if I add an extra prompt at the end like so, both of them re-render when appropriate.

```
      <c-button m-if="store.state.pendingAgree" m-on:click="agree" content="Agree"></c-button>
      <div m-if="store.state.accepted">
        <div class="normal-scene">
          <prompt m-literal:options="store.state.prompts" m-literal:choice="store.state.choice" m-on:choose="choose"></prompt>
        </div>
      </div>
      <prompt m-literal:options="store.state.prompts" m-literal:choice="store.state.choice" m-on:choose="choose"></prompt>
```

This can be seen in my reduced example repo: https://github.com/LeviSchuck/moon-rerender
(for historic purposes https://github.com/LeviSchuck/moon-rerender/tree/2a2504e58bad9c192256bd2abd941456870d2304/ )

Same code, just different `index.html` and `index-works.html`

I think this is happening because it is only checking for changes on `<div m-if="store.state.accepted">` and not its children.

**Comment by LeviSchuck** [comment]
For now, it seems I can work around this bug by making a `display:none` div and putting a flattened extra copy of everything in there 😿

**Comment by kbrsh** [comment]
Odd. I think it's because Monx is analyzing dependencies on the first run, and it doesn't analyze them correctly. I'll have to update it to ensure that they are analyzed every time.

**Comment by kokujin** [comment]
I think I had something similar a few hours ago..

`````
<h3>
    {{store.state.selectedProject }}
</h3>
<ul>
    <li m-for="project in store.state.projects">
        <span>{{  project,title }}</span><br>
    </li>
</ul>
`````
The value of  "store.state.selectedProject" is evaluated,  the for loop is not.

**Comment by LeviSchuck** [comment]
Yeah, for my hack I don't actually have to put my special components in a flat space, I can just do an interpolation of the state values directly and it will behave.

```
       <div style="display:none">
        <!-- This is a hack no nesting here -->
        {{store.state.prompts}}{{store.state.choice}}{{store.state.accepted}}
      </div>
```

**Comment by kbrsh** [comment]
@kokujin Your template `{{  project,title }}` might be invalid.

@LeviSchuck Yeah, that's the only way to resolve that (for now). I'm working on a different API for Monx v1 (it will be compatible with Moon v1).

**Comment by kokujin** [comment]
@kbrsh, sorry about the typo, I had done some heavy editing for the post to simplify, error still persists though.

**Comment by kbrsh** [comment]
Cool. I've been able to reproduce the problem and am currently rewriting Monx for v1.

**Comment by kbrsh** [comment]
@LeviSchuck Can you get the latest version of Monx from the repo and switch to the new API?

The primary change is that there is no `store` option, just add this to the `init` hook:

```js
store.init(this);
```

**Comment by LeviSchuck** [comment]
@kbrsh I've loaded it in, but the transition is not clear to me here.

Could you update the readme in the monx repo accordingly?
I wasn't sure where such is supposed to be called (in reference to `this`), so I tried

```
const app = new Moon({
...
});
store.init(app);
```
But that seem silly considering there is already a `Moon.use(Monx);`

**Comment by LeviSchuck** [comment]
Oh! I see now after re-reading like 3 times.

```
,
  hooks: {
    init: function() {
      store.init(this);
    }
  }
```

Well, I'm not getting console errors anymore at least.
Still, figuring out why things are not showing up compared to my crazy dirty hacks from before half working.

**Comment by kbrsh** [comment]
@LeviSchuck Sorry, I'll make it more clear. I can't update the README because I need a place for the current documentation.

```js
// Define store
const store = new Monx({
  state: {}
});

// Add store to a component
Moon.extend("component", {
  hooks: {
    init() {
      store.init(this);
    }
  }
});

// Add store to root instance
new Moon({
  hooks: {
    init() {
      store.init(this);
    }
  }
});
```

**Comment by LeviSchuck** [comment]
It does work, however It seems I still need to use a `dirty` hack.
That is, I have in my store an integer that gets incremented on the actions that affect this component.
But the component is not re-rendered properly unless I have a `dirty="{{store.state.dirtyCounter}}" attribute on the component.

It may be because the reference does not change?
The way I am editing the particular store item is like `state.scenes[sceneId] = sceneHere`

**Comment by kbrsh** [comment]
Yup, that's because the setter was never called. I have to go out right now, but I can add a method to build all instances.

**Comment by LeviSchuck** [comment]
On checking my hypothesis, it seems that getting and then re-setting the entire `state.scenes` value does not replace the need for my current `dirty` hack.

**Comment by kokujin** [comment]
I'm lost. Should we wait for the new release? I do not fully understand how the hack works.

**Comment by kbrsh** [comment]
@kokujin Are you using the latest build for Moon (the one on this repo)? In that case, you can use the latest build for Monx, as will be compatible with v1.

**Comment by kokujin** [comment]
Oh, ok @kbrsh. I am still using the  0.11 release

**Comment by kbrsh** [comment]
Alright it looks like this issue has been fixed.
