### ISSUE TITLE
Cannot read property 'meta' of undefined

### ISSUE THREAD

**Issue by gernest** [kbrsh/moon#142]
Hey there,

I was trying to  experiment with moonjs. this is my code 

```javascript
const basicTpl=`
<form>
<div class="field">
<label>name</label>
</div>
</form>
`;


Moon.component("basic",{
    template: basicTpl,
    data: function(){
        return {
            name: "gernest"
        }
    }
});
const app=new Moon({
    el: "#app"
});

```
I get this error
```
moon.js:1566 Uncaught TypeError: Cannot read property 'meta' of undefined
```

I have realized if the template string is on the same line the error goes away, but I would like to have multiline templates.

Any ideas?

**Comment by kbrsh** [comment]
Hey!

This happens because the first node Moon encounters is a newline, and uses that as the element since that is the root element.

This is fixed in v1, but for now you can remove the starting newline.

```js
const basicTpl=`<form>
<div class="field">
<label>name</label>
</div>
</form>
`;
```
