### ISSUE TITLE
Checkbox m-bind

### ISSUE THREAD

**Issue by MaxBareiss** [kbrsh/moon#143]
Using the master version, when I `m-bind` a value to a checkbox, it doesn't work. I noticed that the test code for this is commented out - does this mean it'll take a little while to re-implement this? Will this functionality get re-implemented?

**Comment by kbrsh** [comment]
Yup! This will definitely get implemented, but was removed when I began to rewrite Moon. The approach I was using before was pretty slow and hacky, which is why I started from scratch.

I'll keep this open as I need to implement checkbox and radio `m-bind`.

**Comment by kbrsh** [comment]
Bind was removed in v1 in favor of a more explicit design — it can be implemented by changing the `value` and adding an event listener to an input, or by using a higher-order function that generates such event listeners.
