### ISSUE TITLE
Performance: Hoist Static Trees

### ISSUE THREAD

**Issue by kbrsh** [kbrsh/moon#146]
Right now, Moon uses a `dynamic` property to decide if an element is dynamic or not. I think that these trees can easily be hoisted out of the render function, and it can return the same object every time.

The compiler can generate code like:

```js
var render = function(m) {
  var instance = this;
  var staticTrees = render.staticTrees;

  if(staticTrees === undefined) {
    staticTrees = render.staticTrees = [ m("h1", {}, []) ];
  }

  return staticTrees[0];
};

render.staticTrees = undefined;
```

**Comment by LeviSchuck** [comment]
I support this.
