### ISSUE TITLE
add preact in repaint benchmark

### ISSUE THREAD

**Issue by avetisk** [kbrsh/moon#147]
`preact` is strangely missing :)

http://moonjs.ga/docs/overview.html

**Comment by kbrsh** [comment]
That's because I didn't get the time to test it, I only added the size because it was requested in #105. I'll definitely add it here though.

**Comment by kbrsh** [comment]
v1's docs don't have a specific section on performance comparisons to avoid controversy — benchmarks can be inaccurate when used to evaluate real-world performance.
