### ISSUE TITLE
Not an issue, it's a personal suggestion

### ISSUE THREAD

**Issue by AndresSepar** [kbrsh/moon#148]
I like the new way of calling methods, but I prefer to call it in singular **"method"** or **"trigger"** instead of using a plural word **"methods"** because I can only call one method at a time.

```javascript
/* Current method */
instance.methods.oneMethod()

/* Suggestions */
instance.method.oneMethod()
/* OR */
instance.trigger("oneMethod")()
```

What do you think about that?

**Comment by LeviSchuck** [comment]
Personally I prefer the dot version, I'm fine with it even being shortened by a letter
