### ISSUE TITLE
Mounting components V1

### ISSUE THREAD

**Issue by kokujin** [kbrsh/moon#149]
I am trying to mount a few components as such

in my main.js file
``````
 app = new Moon({
         root: "#app-moon",
         hooks: {
             init: function() {
                 _log('APP :: init');
             },
             mounted: function() {
                 _log('APP :: mounted');
             },
             updated: function() {
                 _log('APP :: updated');
             }
         }
     });
``````

In an AJAX resonse
``````
  var tc = Moon.extend("test-comp", {
        template: templates['test.html']
   });

tc.mount('#app-moon');
``````
This only produces an error

``````
TypeError: tc.mount is not a function
    at _initComp (app.js:14318)
    at app.js:14324
    at <anonymous>
``````
Has this changed?  Thanks

**Comment by kbrsh** [comment]
The way you are trying to do it hasn't changed, but v1 actually provides a nicer API for manually mounting components.

There are two ways to do it:

```js
const MyComponent = Moon.extend("MyComponent", {
  props: ["foo"],
  template: "<h1>{{foo}}</h1>"
});

// Preferred method
new MyComponent({
  root: "#mycomponent-app",
  props: {
    foo: "Property Value"
  }
});

// Manually call mount
new MyComponent().mount("#mycomponent-app");
```

**Comment by kokujin** [comment]
That works, but with a difference. The way it was before, without declaring a root attribute. I had the "#app-moon" id attribute on the <body> tag, and any other Moon component declared would just be added to the body.

How can I add several components different components and variations of the same type to a Moon instance container like "#app-moon" on the <body> tag which was how it worked before.

The code below works, using the method with a root attribute and manually mounting
``````
         var TestComp = Moon.extend("TestComp", {
             template: templates['test.html']
         });

         //  new TestComp({
         //      root: ".sparks",
         //      props: {
         //          foo: "Property Value"
         //      }
         //  });
         new TestComp().mount(".sparks");
``````

**Comment by kbrsh** [comment]
Moon components will always replace the element. This is how it works even when you use them in a template like `<TestComp/>`.

If you want to add to a list, you'll have to `appendChild` a node to the wrapper, and mount to that child. An easier alternative would be to use a root Moon instance along with `m-for`.

**Comment by kokujin** [comment]
...or use Moonscript. Got it. Thanks

**Comment by kbrsh** [comment]
HyperMoon*

No problem!
