### ISSUE TITLE
The properties of the components are not accessible from the init hook

### ISSUE THREAD

**Issue by AndresSepar** [kbrsh/moon#150]
```javascript
// moon/src/global/api.js
Line: 100  | MoonComponent.prototype.init
```
It's very important that **init hook** make property values accessible because it contains data that can be processed before mounting the component.

In this line, only the names of the properties are passing but not the values
```javascript
// moon/src/global/api.js
Line: 101  | const options = this.options; //['prop1','prop2','prop3']
```
I think that the solution is simple, you just need to move this process from vdom.js to api.js **hook init**:

```javascript
// moon/src/util/vdom.js
Line: 182  | // Merge data with provided props
...
Line: 188 | // End if conditional
```

**Comment by kbrsh** [comment]
I think you're right. `init` should be called after props are passed. I don't think that the virtual DOM engine is a good place to add it though. Instead, I'll add it when it's processing options.

**Comment by AndresSepar** [comment]
Thanks a lot! Great support!
