### ISSUE TITLE
Alternate templating engine

### ISSUE THREAD

**Issue by kokujin** [kbrsh/moon#159]
Is it possible to configure another templating engine instead of Mustache?

**Comment by kbrsh** [comment]
Do you mean the delimiters?

For example, the delimiters `{, }` would look like:

```html
<h1>{foo}</h1>
```

**Comment by kokujin** [comment]
I just re-read the docs:

> Moon has a custom templating syntax similar to Mustache. 

i'ts not actually the Mustache engine

**Comment by kbrsh** [comment]
@kokujin Ahh, yes. Moon's templating engine is custom-made and a little different from mustache.

**Comment by kokujin** [comment]
I would have to try some things out to solve that problem then. Thanks.
