### ISSUE TITLE
 <p>{{msg}}</p>

### ISSUE THREAD

**Issue by intermundos** [kbrsh/moon#162]
On page load  <p>{{msg}}</p> is show before Moon mounts into app. After short time it injects the msg data. 

How I can avoid showing {{}} templates before Moon is fully loaded?

Thank you for help.

**Comment by intermundos** [comment]
Loading moon.js script to <head> solved it.

Would love to know if there is another, proper way to fix it.

**Comment by kbrsh** [comment]
There is a way! The `m-mask` directive. It is a directive that does _nothing_. But because Moon removes all directives, you can style the `m-mask` directive to be hidden, and it will show after Moon is done mounting.

```js
<div id="app" m-mask></div>
```

```css
[m-mask] {
  display: none;
}
```
