### ISSUE TITLE
compileTemplateExpression contains an infinite loop?

### ISSUE THREAD

**Issue by neilsoult** [kbrsh/moon#164]
https://github.com/kbrsh/moon/blob/master/src/compiler/template.js#L9

Forgive me if I am misunderstanding, but it appears that this `while` loop will never break. The variable `expression` never changes, and so every iteration, `(info = expressionRE.exec(expression))` will always return the same value.

**Comment by kbrsh** [comment]
Ah, that's not an infinite loop. Essentially, the `exec` function will return each match after being called on the same string until it returns `null`. Check out [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec#Finding_successive_matches) for more information on how to find successive matches with `exec`.
