### ISSUE TITLE
Load .moon or .html files from html/js

### ISSUE THREAD

**Issue by eucariop** [kbrsh/moon#166]
Load .moon or .html files directly from html/js. No node.js environment, no loader webpack, no build step.

Sample as templateURL or ng-include allows the user to dynamically load a remote template file at runtime. This seems pretty convenient as a built-in feature:

Support <template>, <script> and <style> support the src attribute.
Module.exports may be a promise.
Support of relative urls in <template> and <style> sections.
Support custom CSS, HTML and scripting languages, eg. <script lang="x/template"> 

I look forward to your comments, regards.

**Comment by kbrsh** [comment]
.moon files were specifically created to be able to precompile components so that they don't have to be compiled at runtime. This sort of defeats the purpose and will make an application really slow.

It would also require loading a ton of dependencies for certain tasks. For example, if you have a component that uses Pug, Stylus, and ES6 with Babel, then Moon would have to:

1. Fetch the component
2. Compile the component to get its' parts
3. Apply the preprocessors (Pug, Stylus, Babel)
4. Scope styles
5. Compile the component template
5. Generate code for the component
6. Execute the code to export the component

This would add a couple _thousand_ lines of code to Moon and would barely work.

**Comment by eucariop** [comment]
Yes, how it works? Can require loading dependences in http loader

1. http request the moon file
2. load the moon file in a document fragment
3. process each section (template, script and style)
4. return a promise to moon.js (async components)
5. then moon.js compiles and cache the component

this example,
const Moon = require("moonjs");
require("./mycomponent.moon")(Moon);

new Moon({
  el: "#app"
});

or using httpLoader().....

new Moon({
   el: '#app',
   components: {
      'mycomponent': httpLoader('mycomponent.moon')
   }
});

or, using httpLoader.register()...

httpLoader.register(Moon, 'mycomponent.moon');

new Moon({
    components: [
        'mycomponent'
     },

or, using httpLoader as a plugin

Moon.use(httpLoader);

    new moon({
        components: {
            'mycomponent': 'url:mycomponent.moon'
        },


in html
<div id="my-app">
    <mycomponent></mycomponent>
</div>

The aim of moon file loader is to quickly test .moon components without any compilation step.
However, for production, I recommend to use webpack module bundler (with moon loader), webpack-simple is a good minimalist webpack config i should look at.

**Comment by kbrsh** [comment]
That won't work. Moon will need to be bundled with _huge_ packages, including Babel, Stylus, Jade, Haml, SCSS, and Less. That's a _lot_ of code being added to Moon for a use case that will help in development. It will still have to compile the template as well. If you'd like to do this on your own, just use [moon-component-compiler](https://github.com/kbrsh/moon-component-compiler) yourself.

I'm still confused though, is running `moon init app` too hard?

**Comment by rizkyramadhan** [comment]
My use-case for this is the user will be able to create a component on-the-fly using our app's  IDE.
Each time user save a component, our IDE will compile it and the resulting file will be injected on user's app.

**Comment by kbrsh** [comment]
I think that instead of being built-in to Moon, you can use [moon-component-compiler](https://github.com/kbrsh/moon-component-compiler) to compile the component. It compiles `.moon` files into code that you can inject however you'd like.

**Comment by kbrsh** [comment]
Closing, as this is definitely not going to be added to the Moon core.
