### ISSUE TITLE
How to check if component is already declared ?

### ISSUE THREAD

**Issue by rizkyramadhan** [kbrsh/moon#168]
Hi 

I want to build dynamic component loader for moon component, so i need to check whether the component is already loaded or not ?

I can't find it in docs..

**Comment by kbrsh** [comment]
There is no way of checking if a component is loaded. That should be something to add in the loader code itself (keep an object containing all of the currently registered components and reference that).

**Comment by rizkyramadhan** [comment]
Or... just expose components global variable into Moon

```

    /* ======= Global Variables ======= */
    var directives = {};
    var specialDirectives = {};
    var components = {};

    Moon.loadedComponents = components; /// add this ?
```

**Comment by kbrsh** [comment]
That's an internal variable used by Moon to store the constructor and options of a component. May I ask what use-case this has? I'm not sure what is preventing you from implementing the store yourself.

**Comment by rizkyramadhan** [comment]
I am implementing the store myself. But it'll be nice if Moon has this capabilities built-in.

**Comment by kbrsh** [comment]
Closing for now as components in v1 can still be added in runtime and require compilation, but am open to discussion.
