### ISSUE TITLE
Modify this.root after being mounted ?

### ISSUE THREAD

**Issue by rizkyramadhan** [kbrsh/moon#172]
Is it safe to modify this.root after being mounted ?
How `updated` lifecycle affects the DOM ?

**Comment by kbrsh** [comment]
It's not safe, as Moon will need access to previous DOM nodes and structure to update correctly. The `updated` lifecycle hook is called after the DOM is updated.

**Comment by rizkyramadhan** [comment]
Quoting your previous answer:

> Updating this.root by appending, removing, or replacing elements will break the next render. So will setting any props on elements.
> 
> It's mostly so you can set stuff like the height and width of the element. You can also access the insert of the component and then render it using a custom render function.

And, how `custom render function` works ? I think it is not even mentioned in the docs.

**Comment by kbrsh** [comment]
So whenever Moon compiles your template, it compiles it into a Javascript render function that returns a virtual DOM.

The example I gave earlier is a good place to start:

```html
<div class="component">
  <m-insert/>
</div>
```

Gets compiled into:

```js
var compiledRender = function(m) {
  var instance = this;
  var staticNodes = instance.compiledRender.staticNodes;
  if(staticNodes === undefined) {
    staticNodes = instance.compiledRender.staticNodes = [];
  }
  return m("div", {attrs: {"class": "component"}}, {}, m.flatten([instance.insert]));
}
```

The `instance.insert` is an array of the virtual DOM nodes that were given by the parent. You can mess around with the compiler by using `Moon.compile`, and add a custom filter for `instance.insert` if you're making a virtual list.

**Comment by rizkyramadhan** [comment]
I see. 

[This page](http://moonjs.ga/docs/compiler.html) should have more example.
And we have to include `instance.insert` to one of the example.

**Comment by kbrsh** [comment]
That page is using a different Moon version (v0.11.0). The v1 development version (master) has multiple breaking changes.

**Comment by rizkyramadhan** [comment]
Is there any docs in progress ? I want to contribute something if can...

**Comment by kbrsh** [comment]
Not really, as the API isn't final yet. Please move this discussion to the [Moon Slack](https://moon-slack.herokuapp.com) as it isn't appropriate for an issue.
