### ISSUE TITLE
instance.set can't cope with array style references

### ISSUE THREAD

**Issue by TotallyInformation** [kbrsh/moon#176]
Hi - loving MoonJS, just starting to work with it, love the simplicity. Perfect as a tool to help with my [uibuilder](https://github.com/TotallyInformation/node-red-contrib-uibuilder/wiki/Example:-MoonJS) for [Node-RED](https://nodered.org/).

I have a UI where I'm receiving input from MQTT over websockets. The data as a 'topic' property that takes the form: `homie/<deviceID>/...`.

To display this, I want to keep an object in my Moon app instance that is key'd on topic. Obviously, JavaScript won't let me do `varName.homie/...` so I use the form `varName['homie/...']`. This is, of course, perfectly valid JavaScript.

However, although instance.set allows me to do `instance.set('varName.propName')`, it is not letting me do `instance.set('varName["propName"]')` which I think it should do (note the nested quotes).

**Comment by kbrsh** [comment]
Glad you like Moon!

Moon doesn't support removing quotations for you, so omitting them should work:

```js
instance.set('varName[propName]');
```

To accomplish this under the hood, there is some hacky Regex replacing and iterating to set the item in the keypath. A cleaner alternative would be:

```js
const varName = instance.get("varName");
varName["propName"] = "foo";
instance.set("varName", varName);
```

They both are the same thing, but the latter looks cleaner. Keep in mind that in v1, keypaths will not be supported in `set`, and `set` will also be able to take in an object.

**Comment by TotallyInformation** [comment]
Ah, OK, thanks for that. If that is doing the same as your second example, I can certainly do that though I think that will create a copy of the variable and I'm doing my best to try and keep memory utilisation down.

I think that your last comment tells me why the next part of my code isn't working! As my var is an object of objects Moon isn't letting me update the object.

The object should look like:

```
{
  "topic1": { "lastupdated": "2017-10-30T10:11:12.409Z", "location": "Living Room" }
  "topic2": { .... }
}
```

But weirdly, I always end up with something like:

```
{
  "topic1": { "lastupdated": "", "location": "" }
  "topic2": { .... }
}
```

I can't quite work out whether that is an artifact of the way that instance.set is working or whether some odd async problem is causing the wrong values to be entered.

One comment that I would make is that the documentation for MoonJS is somewhat "sparse". Some slightly more complex examples might go a long way to helping ;-)

If I can get this working, I will put up the code to GitHub. The first link in my first message already points to a GitHub WIKI page with a simple example. But encouraging some more people to share would be very helpful.

**Comment by kbrsh** [comment]
Cool! It won't create a copy of the object, and will just mutate the current object, and let Moon know that you updated it (`.set` will just set the value to itself). This means that there won't be a memory issue.

As for the second issue, I'm not sure why that happens. How exactly are you updating the objects, and what are the values that you set?

I'll definitely work on adding more complex examples, but I'm currently working on getting v1 fully developed. It has a number of breaking changes that make Moon fundamentally simpler and more flexible.

**Comment by TotallyInformation** [comment]
Thanks for thinking about more examples. I hadn't initially appreciated that you were working on a v1 so I understand.

Thanks for the clarification on .get/.set as well - doubtless I was overthinking things.

I'm not sure why the other issue is happening. And now I've messed around so much that I've probably got myself into a mess. I may have to go back to the beginning. 

How my system works is that I have a library that handles a Socket.IO connection to/from Node-RED. It exposes the msg variable that is sent back and forth along with some additional variables and creates a custom event handler that allows users to easily detect changes to the msg and the other variables.

That way, it is easy to integrate to ANY front-end library whether it is JQuery, MoonJS, Riot, Vue, etc.

So in the mounted hook for my MoonJS app, I create a number of listeners for the variable change events. When triggered a callback is used to update the app's internal variables. Here is an extract of the current code:

```javascript
   hooks: { // Available hooks: init,mounted,updated,destroyed
        
        mounted: function(){
            //console.debug('app mounted - setting up uibuilder watchers')

            this.set( 'feVersion', uibuilder.get('version'))

            // If msg changes - msg is updated when a standard msg is received from Node-RED over Socket.IO
            // Note that you can also listen for 'msgsReceived' as they are updated at the same time
            // but newVal relates to the attribute being listened to.
            uibuilder.onChange('msg', function(newVal){
                console.group('--MOUNTED - MSG RECEIVED --')
                //console.info('property msg changed!', newVal)
                app1.set( 'msgRecvd', newVal)

                // If we receive an MQTT type msg with topic 'homie/<deviceId>/...
                // NB: MoonJS <v1 if needing to set whole topic, use the form:
                //     instance.set("updates[homie/devId]", val)
                //     e.g. no inner quotes
                if ( newVal.hasOwnProperty('topic') ) {
                    let splitTopic = newVal.topic.split('/')
                    let devId = splitTopic[1]
                    if ( splitTopic[0] === 'homie' ) {
                        console.group('HOMIE - ' + devId + '')
                        //console.dir( 'UPDATES:', app1.get('updates') )
                        //let thisUpdate = app1.get('updates' + devId)
                        //console.dir('thisUpdate:', thisUpdate)
                        let homie = app1.get('homie')
                        console.log('HOMIE 0: %o', homie )
                        //if ( thisUpdate === undefined ) {
                        //    console.log('thisUpdate undefined so setting object')
                        //    thisUpdate = {'updated':'', 'location':''}
                        //}
                        if ( !homie.hasOwnProperty(devId) ) {
                            homie[devId] = {'status': 'Initial Creation'}
                            console.log('HOMIE 1: %o', homie )
                        }
                        if ( splitTopic[3] === '$updated' ) {
                            //console.log('setting updated')
                            //thisUpdate.updated = newVal.payload
                            //console.dir('thisUpdate ($updated):', thisUpdate)
                            homie[devId].updated = newVal.payload
                            console.log('HOMIE 2: %o', homie )
                        }
                        if ( splitTopic[2] === '$location' ) {
                            //console.log('setting location')
                            //thisUpdate.location = newVal.payload
                            //console.dir('thisUpdate ($location):', thisUpdate)
                            homie[devId].location = newVal.payload
                            console.log('HOMIE 3: %o', homie )
                        }
                        //console.dir('thisUpdate (final):', thisUpdate)
                        //app1.set('updates.' + devId, thisUpdate)
                        console.dir('homie final:',homie)
                        app1.set('homie', homie)
                        console.groupEnd() 
                    }
                }
                console.groupEnd()                
            })
...
```

I'm fairly sure I've done something stupid. Doubtless it will come to me at some point.

**Comment by TotallyInformation** [comment]
Right, finally spotted it.

I'm afraid the code I gave above wasn't the code that caused the previous issue - please ignore, I'm fairly sure that was something else I did wrong. The code above is probably a bit OTT but it does work - when you haven't made a mistake in the id you were using in your HTML!!

**Comment by TotallyInformation** [comment]
Right so setting an object actually does work correctly as far as I can see.

The following works quite happily:

### index.js
```javascript
const app1 = new Moon({
    el: "#app",
    data: {
        homie       : {} // devId: {updated,}
    }, // --- End of data --- //
    hooks: { // Available hooks: init,mounted,updated,destroyed
        
        mounted: function(){
            //console.debug('app mounted - setting up uibuilder watchers')

            var that = this

            // If msg changes - msg is updated when a standard msg is received from Node-RED over Socket.IO
            // Note that you can also listen for 'msgsReceived' as they are updated at the same time
            // but newVal relates to the attribute being listened to.
            uibuilder.onChange('msg', function(newVal){
                that.set( 'msgRecvd', newVal)

                /** If we receive an MQTT type msg with topic 'homie/<deviceId>/...
                 * NB: MoonJS <v1 if needing to set whole topic, use the form:
                 *     instance.set("updates[homie/devId]", val)
                 *     e.g. no inner quotes
                 */
                if ( newVal.hasOwnProperty('topic') ) {
                    let splitTopic = newVal.topic.split('/')
                    let devId = splitTopic[1]
                    if ( splitTopic[0] === 'homie' ) {
                        let homie = that.get('homie')
                        if ( !homie.hasOwnProperty(devId) ) {
                            homie[devId] = {}
                        }
                        if ( splitTopic[3] === '$updated' ) {
                            homie[devId].updated = newVal.payload
                        }
                        if ( splitTopic[2] === '$location' ) {
                            homie[devId].location = newVal.payload
                        }
                        //uibuilder.set('homie',homie)
                        that.set('homie', homie)
                    }
                }
            })
        } // --- End of mounted hook --- //
    } // --- End of hooks --- //
}) // --- End of app1 --- //
```

### index.html (snippet)
```html
                <table>
                    <tr>
                        <th>Device ID</th><th>Last Update</th><th>Location</th><th></th>
                    </tr>
                    <tr m-for="data,topic in homie">
                        <td>{{topic}}</td><td>{{data.updated}}</td><td>{{data.location}}</td>
                    </tr>
                </table>
```

And the data is sent in 3 test messages:

```javascript
node.send({
    "payload": "2017-10-30T10:11:12.409Z",
    "topic": "homie/DEVICE1/$stats/$updated"
})
node.send({
    "payload": "Living Room",
    "topic": "homie/DEVICE1/$location"
})
node.send({
    "payload": "Hall",
    "topic": "homie/DEVICE2/$location"
})
node.send({
    "payload": '"2017-10-30T10:11:12.409Z"',
    "topic": "homie/DEVICE2/$stats/$updated"
})
```

I get a nice table for my troubles.

**Comment by kbrsh** [comment]
Glad you were able to figure it out! Let me know if you find any bugs or have any things you find hard to accomplish with Moon.
