### ISSUE TITLE
[Question] Can we use Vuetify with MoonJS?

### ISSUE THREAD

**Issue by vinaybedre** [kbrsh/moon#182]
Hi,

I read that MoonJS is stripped down version of VueJS, similar to Preact for React. 
Can we use well known UI framework Vuetify(vuetifyjs.com) with Moon?

**Comment by Grafikart** [comment]
I don't think so. 

MoonJS is his own thing, it looks similar to VueJS but this is not a drop in replacement (like zepto for jQuery).

**Comment by kbrsh** [comment]
Yep, @Grafikart is correct.

Moon is not meant to be a drop-in replacement for Vue, but is rather a library inspired by it.
