### ISSUE TITLE
Moon does not compile first component in template

### ISSUE THREAD

**Issue by rizkyramadhan** [kbrsh/moon#183]
See this https://jsfiddle.net/qg7pw9cs/

I expected to see this html:
```
<div id="app"><div>Hello</div></div>
```

Current compiled result is:
```
<div id="app"><comp2>Hello</comp2></div>
```

**Comment by rizkyramadhan** [comment]
When I change into https://jsfiddle.net/qg7pw9cs/1/

It renders as intended.

**Comment by kbrsh** [comment]
That's intended behavior for v1. A component cannot contain another component as it's root element. It will be included in the v1 documentation when released.
