### ISSUE TITLE
Shadow DOM in components

### ISSUE THREAD

**Issue by telemac** [kbrsh/moon#184]
Hi !

Can moon create components with their content in shadow dom ? and upgrade components, as it is possible with custom elements ?

Regards
Alexandre

**Comment by kbrsh** [comment]
Moon's virtual DOM engine cannot create content in shadow DOM, and due to browser limitations, I'm not considering adding it right now. You can control elements and their shadow DOM inside of hooks and methods—Moon will simply ignore them.

**Comment by kbrsh** [comment]
v1 is compatible with shadow DOM running alongside Moon but does not use it.
