### ISSUE TITLE
there is an error in dist/moon.min.js

### ISSUE THREAD

**Issue by RemyNoulin** [kbrsh/moon#186]
replace "undefined"==typeof with "object"==typeof

The version on the CDN is ok.

**Comment by kbrsh** [comment]
That's not an error—if `module` is `undefined` then it will create a global variable (usually `window.Moon`), if not then it will create it on `module`.

**Comment by kbrsh** [comment]
You're mounting it onto `#app1`, which doesn't seem to exist in the code you gave. Try using the development version—it has warnings for these types of situations.

**Comment by RemyNoulin** [comment]
Sorry, github removed some parts of the code, the orignal code is:
`
<body>
<script src="./dist/moon.min.js"></script>
<div id="app1">
  <p>{{msg}}</p>
</div>
<script>
const app1 = new Moon({
  el: "#app1",
  data: {
    msg: "Hello Moon!"
  }
});
</script>
</body>
`

I run this code in the browser (no node involved), replacing ./dist/moon.min.js with https://unpkg.com/moonjs make the code work.

I suggest you add the minified and browserified moonjs file in the git.

**Comment by RemyNoulin** [comment]
Fixed the markdown problem :), the orignal code is:

```
<body>
<script src="./dist/moon.min.js"></script>
<div id="app1">
  <p>{{msg}}</p>
</div>
<script>
const app1 = new Moon({
  el: "#app1",
  data: {
    msg: "Hello Moon!"
  }
});
</script>
</body>
```


I run this code in the browser (no node involved), replacing ./dist/moon.min.js with https://unpkg.com/moonjs make the code work.

I suggest you add the minified and browserified moonjs file in the git.

**Comment by kbrsh** [comment]
It works fine, [here's](https://jsfiddle.net/y26bakd5/) an example jsFiddle. Using the latest Git version will not work, since that is the latest build of v1 (which has a number of breaking changes to the API and will likely not work with v0.11.0 code).

**Comment by RemyNoulin** [comment]
That's right, I'm using the using on master. Thanks for your answers!

**Comment by kbrsh** [comment]
No problem.
