### ISSUE TITLE
Add links to source code for examples

### ISSUE THREAD

**Issue by skilfullycurled** [kbrsh/moon#189]
Would it be possible to have links to the source code for the [examples](http://moonjs.ga/docs/examples.html)?

I can view all of the code in the inspector but it would be nice to see how it is structured.  I tried looking up the moon.js version of TodoMVC but it doesn't appear to be available in their [list of choices](https://github.com/tastejs/todomvc/tree/master/examples).

Thanks!

**Comment by kbrsh** [comment]
Moon hasn't been submitted to TodoMVC yet (#86), and the source code for all of the examples are available in the `gh-pages` branch of this repo.
