### ISSUE TITLE
New line in Component template property

### ISSUE THREAD

**Issue by ksanderer** [kbrsh/moon#192]
```
Moon.component("test-comp", {
    data: function(){
        return {
            test: "asd"
        }
    },

    template: `<div><a myprop="asd"
                                 m-literal:class="{'active': true}">{{ test }}</a></div>`,
});
```

Gives me:

![2017-12-04_23-52-49](https://user-images.githubusercontent.com/1606635/33575713-989bb546-d94e-11e7-809f-a06d6a578530.png)

But for `<div><a myprop="asd" m-literal:class="{'active': true}">{{ test }}</a></div>` it works as expected.

Not sure it's bug or feature, but it took me more than an hour to figure out what is wrong.

**Comment by kbrsh** [comment]
It's a known bug that will be fixed along with #178 when I rewrite the lexer.
