### ISSUE TITLE
moon@master Event System Broken

### ISSUE THREAD

**Issue by hypercub3d** [kbrsh/moon#193]
Hi,

After encountering the event bug referenced in #132, I decided to try the latest master branch to see if the bug was corrected there.

I've encountered a few issues with the event system in the master branch:

1. The event system no longer passes an event object to the event handler.
2. When emitting an event with a payload, the payload is not passed to the event handler.

Here is a quick fiddle demonstrating both issues.

https://jsfiddle.net/hypercub3d/jpnjtLpc/

At this point, the events in both the 0.11.0 branch and the master branch seem to be broken.

**Comment by kbrsh** [comment]
1. This is intended to allow for extra optimization as the event isn't always used. To pass it, you can use the special `event` variable: `m-on:click="method(event)"` This was implemented in dc360377a5a4081bf38e2409c161b81ef5c89470.
2. You can use the `event` variable to capture the payload when adding an event to a top-level component.

[Here](https://jsfiddle.net/jpnjtLpc/1/) is a fixed example.

**Comment by hypercub3d** [comment]
Thank you for the quick reply.

I see, that makes sense. I could not find this documented anywhere, hence the confusion.

**Comment by kbrsh** [comment]
The master branch is not documented yet, it's the current development of v1.
