### ISSUE TITLE
Hoisted VNode Mismatch

### ISSUE THREAD

**Issue by kbrsh** [kbrsh/moon#195]
In certain cases, the nodes in hoisted vnodes are updated before they are reached, causing the node to be outdated once it is reached.

I've managed to track down the problem and draft a fix.

1. When encountering a hoisted vnode being created:
    1. Clone `vnode.data.node`.
    2. Attach event listeners to cloned node.
    3. Use cloned node as created node.
2. When encountering a hoisted new vnode that is not the same as the old vnode:
    1. If not appending, only replace it (no text, component, or child updates). Run `newVNode.data.hoisted = newVNode.data.node`.
3. When encountering a hoisted old vnode that is not the same as the new vnode:
    1. If removing, use `oldVNode.data.hoisted` as `oldVNode.data.node` if available. If not available, use `oldVNode.data.node`.
    2. If it is not removing, only replace it (no text, component, or child updates). Use `oldVNode.data.hoisted` as `oldVNode.data.node` if available. If not available, use `oldVNode.data.node`.

**Comment by rizkyramadhan** [comment]
any progress on this ?
