### ISSUE TITLE
Delimiter options for template

### ISSUE THREAD

**Issue by jmptrader** [kbrsh/moon#196]
Hello,
In VueJS you can change delimiters with

new Vue({
  delimiters: ['${', '}']
})

I see in **constants.js** that exists  => openRE & closeRE.

You can consider an configurable option.

Thank's

**Comment by kbrsh** [comment]
While there are constant regular expressions, the template compiler relies on their lengths to perform string operations correctly.

Also, I'm changing up the template engine for v1, and the current template system will not be compatible with the new one. I _might_ considering adding custom delimiters in that template engine, but we'll cross that bridge once we come to it.

**Comment by kbrsh** [comment]
Closing in favor of #221
