### ISSUE TITLE
In components, data must be a function????

### ISSUE THREAD

**Issue by guleweidog** [kbrsh/moon#197]
```html
<div id="example1">
	<simple-counter></simple-counter>
	<simple-counter></simple-counter>
	<simple-counter></simple-counter>
</div>
```

```js
var data = { counter: 0 }

Moon.extend('simple-counter', {
	template: `<button m-on:click="instance.set('counter', counter+1)">{{ counter }}</button>`,
	data: data
})

new Moon({
	root: '#example1',
})
```

**Comment by kbrsh** [comment]
What's the problem here? Data _must_ be a function as stated in the documentation. The dev version of Moon `moon.js` gives an error if you don't. If you ignore the error, then the data will be globally shared across all component instances.

**Comment by guleweidog** [comment]
look at [this fiddle](https://jsfiddle.net/bk0vxd4L).

Data is not function, and there is no interaction between components. So data is function is not necessary??

**Comment by rizkyramadhan** [comment]
That's a bug!

**Comment by kbrsh** [comment]
@guleweidog @rizkyramadhan It's working as expected. In the console, Moon throws an error.

```
[Moon] ERROR: In components, data must be a function returning an object
```

**Comment by sisou** [comment]
It can be discussed if Moon should fatal when data is not a function (I think it shouldn't, the Error in the console is enough), but it will work with the static data object. Just don't complain that it shares state between components, if you do that ;)

**Comment by samuelgozi** [comment]
Why don't just copy the object, and use the declared one as a reference?

**Comment by sisou** [comment]
Because deep-cloning an object comes with it's own set of problems and boilerplate code, so just having a function return a new object is much cleaner actually.

**Comment by samuelgozi** [comment]
For some reason i was sure that `Object.assign()` was ES5, but its not...
