### ISSUE TITLE
m-else directive not working

### ISSUE THREAD

**Issue by adamspruijt** [kbrsh/moon#198]
With the below portion of code, both part of the template show when "item.memberID" exists.

`<a m-if="item.member" href="{{item.member.url}}">{{item.member.title}}</a>`
`<span m-else>{{item.venue.title}}</span>`

Instead I must do the following
`<a m-if="item.member" href="{{item.member.url}}">{{item.member.title}}</a>`
`<span m-if="!item-member">{{item.venue.title}}</span>`

No errors or warning appear in the dev console

**Comment by sisou** [comment]
`m-else` is not implemented and also not documented anywhere. Sorry.

**Comment by kbrsh** [comment]
@sisou is correct—it isn't implemented in v0.11.0. The `m-else` directive will be available in v1.
