### ISSUE TITLE
Problem using m-for in a template

### ISSUE THREAD

**Issue by kokujin** [kbrsh/moon#205]
Moon is emitting this error in the console:

``````
moon.js:179 [Moon] ERROR: The item "arr" was not defined but was referenced

``````
I am trying to render loops in a template, here is a quick example below:
``````
  Moon.component('my-component', {
            template: `<div>
                <p>This is a Component!</p>
                <select>                   
                    <option m-for="item in arr" value="{{item}}">{{item}}</option>
                </select>
                <span>End</span>                
            </div>`
        });

        const app1 = new Moon({
            el: "#app1",
            data: {
                msg: "Hello Moon!",
                arr: [4, 5, 6]
            }
        });
``````
Anyone know what I am doing wrong? Thanks

**Comment by kbrsh** [comment]
The component `my-component` does not have a property called `arr`, which you are trying to loop through:

```html
<option m-for="item in arr" value="{{item}}">{{item}}</option>
```

If you are accepting `arr` as a property in your main instance template, you have to declare it as an option.

```js
Moon.component("my-component", {
  props: ["arr"]
});
```

**Comment by kokujin** [comment]
I tried that out and got another error:
``````
moon.js:367 Uncaught TypeError: Cannot read property 'type' of null
``````

**Comment by kbrsh** [comment]
Can you send a reproduction using [jsFiddle](https://jsfiddle.net)?

**Comment by kokujin** [comment]
Here is a simple fiddle, https://jsfiddle.net/56puthx5/

**Comment by kbrsh** [comment]
You declared the `arr` prop, so that the `my-component` component can render any array that is passed to it. To pass the array to the component, you can use an attribute on the element, and in this case `m-literal` for the array.

```html
<my-component m-literal:arr="arr"></my-component>
```

**Comment by kokujin** [comment]
Thanks

**Comment by riiccardo** [comment]
@kbrsh can u update @kokujin jsfiddle ???
