### ISSUE TITLE
SSR workflow?

### ISSUE THREAD

**Issue by kokujin** [kbrsh/moon#206]
Is there a recommended workflow to prerender/ precompile Moon components? I would like to render and hydrate a few components that have SEO relevant blocks. At the moment we have:

- https://github.com/kbrsh/moon-ssr. But this does a little too much I think.
- https://github.com/kbrsh/moon-component-compiler
- http://moonjs.ga/docs/compiler.html. 

I was thinking of using the moon-component-compiler in a custom build script, but the docs on this module are very sparse. Thanks

**Comment by kbrsh** [comment]
Prerendering and precompiling are different things. Moon works by compiling your template into JavaScript and then calling this generated function to update the DOM.

To _precompile_, you can use `Moon.compile` (`moon-component-compiler` uses this under the hood and is intended to compile `.moon` single-file components). Run `Moon.compile(template)` and pass the outputted JavaScript function code in the `render` option of an instance.

To _prerender_, meaning to convert a component to HTML, you can use `moon-ssr` by running:

```js
MoonSSR.renderToString(instance);
```
