### ISSUE TITLE
MoonJs Store

### ISSUE THREAD

**Issue by herOwOw** [kbrsh/moon#207]
Hey, thx for this awesome framework , i have a question or at least y can add it as a feature maybe later on , can we passe multiple store in MoonJs ? 
i created two stores and put them into array/object and passed them into store attribute so i got this  "o.install is not a function..",  i believe it can only handle only store

**Comment by herOwOw** [comment]
i create a store that have two state and these state are apiData , appData and they are both requiring Monx and i required them inside the store file and it works :)

**Comment by rizkyramadhan** [comment]
Yup, I ask @kbrsh for this, and maybe we will get something like multiple module in the future. 

The internal working of monx makes it impossible to work with multiple store.

**Comment by kbrsh** [comment]
I'm planning on adding a module system @herOwOw @rizkyramadhan—but Monx is second priority for me right now as I'm currently rethinking my goals for Moon and am designing a new API that's a little different from what's already out there.
