### ISSUE TITLE
what happened with moon's website ?

### ISSUE THREAD

**Issue by herOwOw** [kbrsh/moon#208]
the website not working!

**Comment by kbrsh** [comment]
Hey @herOwOw! Thanks for bringing this to my notice—it looks like an advertiser stole the domain (one of the many risks of having a free one).

I'll try fixing this as soon as possible.

**Comment by kbrsh** [comment]
For now, you can visit it here: [kbrsh.github.io/moon](https://kbrsh.github.io/moon)

I'll keep this open until I can find a new domain name.
