### ISSUE TITLE
can't access props inside hooks or a methods

### ISSUE THREAD

**Issue by herOwOw** [kbrsh/moon#209]
wanted to use url prop's value to the mounted or methods to call it later ,i provide a gist link bellow: https://gist.github.com/herOwOw/172042218388f2f6942c05d1792536ef

url shown in h1 tag but not in init's hook or methods

**Comment by kbrsh** [comment]
I don't know if you've figured it out yet, but you have to use `this.get("url")`, everything else looks fine.
