### ISSUE TITLE
Isomorphic?

### ISSUE THREAD

**Issue by davidbwaters** [kbrsh/moon#212]
Hi, I'm still wrapping my head around the universal web app build.  I was wondering if Moon SSR needs any special setup aside from the popular dual webpack setup to be used isomorphic-ly.

**Comment by kbrsh** [comment]
Moon SSR can be used to render any Moon instance to an HTML string. Build tools are not required. Instead, all you need is a Moon instance and can render it with any server.

**Comment by davidbwaters** [comment]
Okay.  One thing I notice is that it looks like once the scripts load on the frontend (if supported) and the page becomes interactive, the content is replaced.  If I am understanding correctly, I believe Vue compares/diffs what elements exist and only loads whats remaining.  This is why projects like Next.js/Nuxt.js use the hybrid approach for fast initial load with SSR (no blank page) and the client takes over once loaded and the app is interactive.  Could Moon and SSR be used like this, running the same code on the client and server?

**Comment by kbrsh** [comment]
Yup! Moon will "hydrate" the already-loaded DOM and will only render the remaining parts of the app, allowing the same code to be used on the client and server.
