### ISSUE TITLE
dist on Github does not work

### ISSUE THREAD

**Issue by buckle2000** [kbrsh/moon#214]
The two files `moon.js` and `moon.min.js` [here](https://github.com/kbrsh/moon/tree/3365188de2791a3373e9d0ab03ee5ef12c67778a/dist), for some reasons, does not work with this example:
```html
    <div id="app1">
        <p>{{msg}}</p>
      </div>
    <script src="moon.min.js"></script>
    <script>
    const app1 = new Moon({
        el: "#app1",
        data: {
            msg: "Hello Moon!"
        }
    });
    </script>
```
The file from unpkg works.

**Comment by kbrsh** [comment]
That's because the version on the `master` branch is currently being developed—it's the code that will be put in to v1. The actual v0.11.0 release is on Unpkg, NPM, or on the git releases.

**Comment by buckle2000** [comment]
Thanks. Can you mention that "The master branch is not stable" in README?

**Comment by stephen-goveia** [comment]
@kbrsh So... when is v1 coming...? :)

**Comment by kbrsh** [comment]
Hey everyone, sorry to keep you all hanging on v1. It was originally planned to be released early this year but I'm still not so sure about it.

I made a mistake by building so many features and creating so many breaking changes that keep on adding up—in the upcoming releases Moon will be updated in smaller increments.

I'm currently busy with school and travel but am working hard to find the time to work on Moon. I'm drafting a new API that should help make it much simpler to get started with—Moon is going in a different direction than Vue.

Once again, I apologize for not keeping you all updated and hope to get some time to work on Moon this month. Feel free to hop into the [Moon Slack](https://moon-slack.herokuapp.com) to discuss the future of Moon with me.

**Comment by kbrsh** [comment]
@buckle2000  @stephen-goveia v1 is released! :tada:
