### ISSUE TITLE
Extend a Component

### ISSUE THREAD

**Issue by mfaessel** [kbrsh/moon#215]
Hi,

How can i extend a component ?

Would like to create a reusable and extendable UI lib for MoonJS.
ssuch as "myprogressbar" extending "progressbar"

Regards,
Martial

**Comment by kbrsh** [comment]
Components are meant to be used and extended with props. A component can behave differently depending on the props it is passed, so you could make a "progressbar" component that is customizable with different props that you can pass to it.

```html
<progressbar foo="example" bar="true"></progressbar>
```

**Comment by mfaessel** [comment]
Thank you for the detail explanation !
