### ISSUE TITLE
Custom delimiters

### ISSUE THREAD

**Issue by kokujin** [kbrsh/moon#221]
I noticed that support for custom delimiters has been removed in the latest release, is there a workaround? I use the Nunjucks templating engine which uses the same delimiters. Thanks

**Comment by kbrsh** [comment]
There is currently no workaround but it may be possible to add them in v1.

**Comment by kbrsh** [comment]
I don't think I'll add custom delimiters because of how closely integrated they are with the compiler. If this becomes a big enough issue then I might consider it, but for now I'm closing this.
