### ISSUE TITLE
how to use vanila and jquery plugin in Moon.js

### ISSUE THREAD

**Issue by riiccardo** [kbrsh/moon#223]
hey tnx for u greate and lightweight js library i read the full documentaion ( cuz it's so small doc )

i dont see the doc about jquery and vanila usage in moon js

pls include more example..

thanks for helping

**Comment by kbrsh** [comment]
You can use JQuery by accessing `this.$el` from a Moon component instance in the `mounted` hook and then initialize the plugin on a specific element. Here's an example of using `select2` with Moon: [jsfiddle.net/sjtr2vgw](https://jsfiddle.net/sjtr2vgw/).

**Comment by riiccardo** [comment]
Thanks for it :heart: 

Another qustion I have is how to use separate files for components like 
dropdown.js, tooltip.js, and something like that 

And import in generalFile.js like react.js

Import dropdown from "dropdown.js"

**Comment by kbrsh** [comment]
No problem!

You can use single-file components using [Moon CLI](https://github.com/kbrsh/moon-cli), or do something like this:

```js
// dropdown.js

export default {
  template: `<div>Dropdown</div>`
};
```

```js
// index.js

import Moon from "moonjs";
import dropdown from "dropdown.js";

Moon.component("Dropdown", dropdown);

new Moon({
  el: "#app",
  template: `<div><Dropdown/></div>`
});
```

**Comment by riiccardo** [comment]
Thank you very much for responding quickly,
               [ componetName ⬇️   --   and what is this 👇  ? ]
`Moon.component("Dropdown",           [ dropdown ]);`


i see diffrent doc about components, [dropdown] in top code is template?
`Moon.component('my-component', {
  template: "<p>This is a Component!</p>"
});`

-------------------------

another qustion moon.js, dont need compiler or babel ?

need webpack or gulp or something like it ?

--------------------

another qustion about moonjs router after router change form /home to /articles
how to reinit javascript code to work again and dont need reload the page to work

**Comment by kbrsh** [comment]
The component API looks like this: `Moon.component(componentName, componentOptions)`. `componentOptions` contains all options for a component similar to the ones of the root Moon instance.

Moon has a built-in compiler for Moon templates ([more information](https://kbrsh.github.io/moon/docs/compiler.html)).

I don't get what you're asking here. Moon router doesn't reload the page but rather manipulates the current URL while keeping all JavaScript loaded.

Let me know if that answers your questions :)

**Comment by riiccardo** [comment]
As you said, I use moon-cli

i understand the compiler so so :) but the doc...

And I'm having trouble with it, but it's more annoying is small documentation and advance examples for beginners

**Comment by kbrsh** [comment]
Moon CLI components expose a different API:

```js
// dropdown.js is compiled to something like this
export default function Dropdown(Moon) {
  Moon.component("Dropdown", { template: `<div>Dropdown</div>` }); // usually template is compiled to render()
};

// it can be used like this
import Moon from "moonjs";
import Dropdown from "dropdown.js";

Dropdown(Moon);
```

I'm sorry for the small documentation — I'm the only person writing it and am not planning to add more as I'm [rewriting Moon](https://github.com/kbrsh/moon/tree/rewrite) and am writing the documentation for that instead.
