### ISSUE TITLE
i have many event on elements how to handle it with m-on:click,focus,change,blur,resize,keydown ??

### ISSUE THREAD

**Issue by riiccardo** [kbrsh/moon#224]
im using moon.js and search for this isssue on web but do'nt find anything
here is simple code in your website i use
``` html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>moon</title>
  </head>
  <body>

    <div id="app">
      <h1 class="msg">{{msg}}</h1>
      <input type="text" m-model="msg">

      <button m-on:click="changeMessage" m-on:blur="" m-on:resize="" m-on:focus="" m-on:keydown="">Click mE</button>
    </div>

    <script src="js/moon.min.js"></script>
    <script src="js/moon-router.min.js"></script>
    <script src="js/app.js"></script>
  </body>
</html>

```
``` javascript
const app = new Moon({
  el: "#app",
  data: {
    msg: "Hello Moon!",
    clicked: false
  },
  methods: {
    changeMessage: function(msg) {
      this.set('msg', ["Set New Message"]);
      const element = document.querySelector('.msg');
      element.classList.add('good');
    }
  }
});
```

issue-1 :arrow_up:  : for each event we must use `m-on` ? or we can use `element.addEventListener("click blur focus change", function(){
})`

issue-2 :arrow_right:  : and how run public or private methods without any event in methods ?
like resize 

issue-3 :arrow_down:  : i want to create some components like react components here my codes
and add tag inside of componet not with data

``` javascript
Moon.component('collapsible', {
  props: ['title', 'desc'],
  template: `<div class='collapsible'>
              <h1 class="title">{{title}}</h1>
              <p class="description">{{desc}}</p>
            </div>`,
  data: {
    title: "", 
    desc: ""
  },
methods: {
     showCollapse: function() {},
     hideCollapse: function() {}
  }
});
```
and html file
``` html
<div id="app">
      <collapsible title="collapsible">
           <h1>i want this to add content inside of components child tag</h1>
           <p>and i want to add content in it not with data and methods</p>
      </collapsible>
</div>
```
i want to add title and description for each collapsible components into of these tag ==> [ h1, p ] not data

``` javascript
data: {
  title: "collapsible components",
  desc: "collapsible description"
}
```

issue -4 : collapsible must create as component or as plugin ?????
`Moon.component('collapsible')` or `Moon.use(collapsible);` omfg im so confiused :disappointed:  :cry:  :sob:

**Comment by kbrsh** [comment]
1. `m-on` is used for adding event listeners for any event, so yes — you use `m-on`
2. You can't run other methods because Moon doesn't have any way of accessing them. Just do something like this:

   ```js
   const privateMethod = function() {};

   new Moon({
     methods: {
       privateMethod
     }
   });
   ```

3. This is shown in the documentation for [slots](https://kbrsh.github.io/moon/docs/components.html#slots).
4. Once again, this is shown in the documentation for [components](https://kbrsh.github.io/moon/docs/components.html).

Monkberry also has a compiler for `.monk` files to `.js`. Moon does something similar for Moon templates. Check out `moon-component-compiler` for some examples. Here is one:

```html
<!-- header.moon -->
<template>
  <h1>{{content}}</h1>
</template>
<style scoped>
  h1 {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;
    font-weight: 200;
    font-size: 100px;
    color: #414141;
  }
</style>
<script>
  exports = {
    props: ["content"]
  }
</script>
```

Compiles to:

```js
<!-- header.js (beautified) -->
var options = {};
options = (function(exports) {
  exports = {
    props: ["content"]
  };
  return exports;
})({});
options.render = function(m) {
  var instance = this;
  var content = instance.get("content");
  return m(
    "h1",
    { attrs: { class: "m-scope-vhb1wnfq81oe" } },
    { shouldRender: true },
    [m("#text", { shouldRender: true }, "" + content + "")]
  );
};

module.exports = function(Moon) {
  Moon.component("header", options);
};
```

```css
h1.m-scope-vhb1wnfq81oe {
    font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen,Ubuntu,Cantarell,"Fira Sans","Droid Sans","Helvetica Neue",sans-serif;
    font-weight: 200;
    font-size: 100px;
    color: #414141;
}
```

**Comment by riiccardo** [comment]
before everything thanks for response 👍 

can we use simple tag like header insead of template ? && after compile named like file name ?

my mean => before compile `<template>` ==> after compile ==> template transfrom to file name(header.moon) ? `<header>` ? Because we did not specify in the `.moon` file what the name of the component is

``` javascript 
module.exports = function(Moon) {
  Moon.component("header", options);
};
```
What is your suggestion ? use `moon-cli` like most js librarys and bundle all scripts OR include production scripts files `moon.min.js` & `moon-router.min.js` ?

**Comment by kbrsh** [comment]
A single file component is named from the filename (`header.moon`). The `template`, `style`, and `script` tags are used because they mark the different parts of the component.

`moon-cli` already bundles the scripts together. In a production setting I'd recommend using the CLI as it precompiles your templates. For simple experiments you can just use the browser version, trading off convenience for performance.
