### ISSUE TITLE
How to use m-for in component template using Webpack

### ISSUE THREAD

**Issue by riiccardo** [kbrsh/moon#226]
All details are given in jsfiddle pls take a look

[JsFiddle Here](https://jsfiddle.net/0ung3xkh/50/)

my problem is similar issue #205 but with **a little bit of difference**. i dont get logic of `m-for` and `item` or `every name we want and not item` or `item in items` ???
`list in lists` or `item in lists` 

like moon exampls `record in commits`

pls explain `m-literal:list="list"` too 

thanks pls help 😢

**Comment by kbrsh** [comment]
Check [this](https://jsfiddle.net/0ung3xkh/55/) out for an annotated example. Let me know if I answered your question.

**Comment by riiccardo** [comment]
[MoonIssue.zip](https://github.com/kbrsh/moon/files/2093749/MoonIssue.zip)
**pls download file and use `npm install` then use `npm run dev`**

in this case
i provide file issue if parent and child and general moon is separate files like
* app.js
     * pages => parent.js
          * parentComponent => child.js

**Comment by kbrsh** [comment]
1. Props are like arguments you pass to a component. As a result, the root instance and parent component do not require it.
2. That's because it is rendering the list prop provided to it by the root Moon instance.
3. Here's a better way of saying it — the root Moon instance is a component.

**Comment by riiccardo** [comment]
You see `MoonIssue.zip` ? What is your idea about it ?  

I'm beginner pls provide an example or explain more 

About what is root ? General moon ( `new Moon` )??

Another thing I get from ur comment ( **maybe understand maybe not** ) we can use new Moon in another component OR pass the `root: "#target"` option in Moon.component ?

**Comment by riiccardo** [comment]
Pls help to pass this problem I swear the god  don't open new issue :laughing: :cry:

**Comment by kbrsh** [comment]
I don't currently have time to look into your case specifically. Root is `new Moon`. Basically, there is a class `Moon` that every component is a subclass of. This means that running `new Moon` creates a new instance of this class, _and_ running `Moon.component` and using it in a template will create a new instance of the class. As a result, `new Moon` and `Moon.component` take the same options, with the exception of `el`.

The props are again like arguments to a function. Think of a component like a function of state — you can pass it arguments.

```js
function child(prop) {
  console.log("child created with " + prop);
}

function parent() {
  return child("hello");
}

function root() {
  return parent();
}
```

Just like `parent` provides an argument to `child`, `root` could provide the argument to parent in order to pass it down further. This is how a component works. You declare the `props` that it takes as arguments and any component can pass them down to children.

**Comment by riiccardo** [comment]
@kbrsh 

pls look this [CODEPEN](https://codepen.io/riccardo051/pen/wXeJNV)

Have a look at this file as `MoonIssue.zip`

Do not need to do anything, just look at one

i just copy ur jsfiddle and I separated the files from each other, and using module type file and imported to one codepen

it is the `childComponent` => [**`Child.js`**](https://codepen.io/riccardo051/pen/LrLWJe)

and its the `parentComponent` =>[**`Parent.js`**](https://codepen.io/riccardo051/pen/qKjrLp)

and its `root` or `new Moon` => [**`App.js`**](https://codepen.io/riccardo051/pen/wXeJNV)


pls read this one too:

if you look at your jsfiddle all the `component` and `root` [ **placed in one script tag** ] and  components are not **_Separate Files_**  

[ this issue seems to come about when components are **_Separate Files_**]

like `child.js` - `parent.js` - `app.js`


its my jsfiddle you update... 

``` javascript
<script>
  'use strict';
  // child section component ============================
  const myComponent = Moon.component('my-component', {
    props: ["list"],
    data: function() {
      return {
        list: ['Item - 1', 'Item - 2', 'Item - 3', 'Item - 4']
      }
    },
    // Moon doesn't support m-for as the root element, so I wrapped it in a div
    // Also, you can bind any variable in `m-for`
    // Syntax: `{name} in {array}`
    template: `<div><div class="m-for__problem">
                <ul>
                  <li m-for="item in list">{{item}}</li>
                </ul>
            </div></div>`,
    methods: {
      axiosInComponent: function() {
        alert('wtf');
      }
    },
    hooks: {
      mounted: function() {
        this.callMethod("axiosInComponent", []);
      }
    }
  });


  // parent section and component ========================
  const parentComponent = Moon.component('parent-component', {
    props: ["list"],
    template: `<div class="parent">
  						<my-component m-literal:list="list"></my-component>
            </div>`
  })


  // general section
  const app = new Moon({
    el: "#app",
    data: {
      loopProblem: "i have problem in m-for, for using it in component template u explain it in issue but i dont realy have any idea; https://github.com/kbrsh/moon/issues/205, we must just use `items` like `item in list` ??? because i see diffrence m-for in your examples like `record in commits` realy i dont understand m-for logic :|, let me explain my [ PROBLEM ] => i want to use m-for in components and just fix it in component section not in general `new Moon`, my mean dont need to add two props in component section and general app section, pls explain more about m-literal:list='list', why i create two components ?? because i have too... im using webpack and module scripts for separate files for clean code and simple editing and parent component wrap all child component and just have to write one component tag in html and dont need more component tag in html and parent tag maybe have more componet like header main footer, i use one component just for explain problem..",
      list: [1, 2, 3] // Here I added the list variable instead of a prop because you need to define it somewhere
      // M-literal passes down a prop as a literal expression instead of a
      // string. So doing prop="hello" would pass the javascript string
      // "hello". Doing m-literal:prop="hello" would pass the VARIABLE
      // "hello" from the `data`
    }
  });

</script>

```

**Comment by riiccardo** [comment]
If I want to explain briefly:

1- i just copy each section in jsfiddle and created separate files like `child.js` - `parent.js` and `app.js`

2- i imported them to one the `root` or `new Moon`

3- this issue apear when we use separate files and console threw this error: Moon is not define

**Comment by kbrsh** [comment]
Moon registers components globally, you don't need to `import` them to use them. You just need to be able to get the file running to create the component on the `Moon` library.

```js
// component.js

export function InitComponent(Moon) => {
  Moon.component("Component", { /* options */ });
};

// app.js

import { InitComponent } from "./component.js";

InitComponent(Moon);

// you can now use the component
```

**Comment by riiccardo** [comment]
i change my all files working on moon to your comment but still have problem

even i changed my codepen to `export function` but still have error 

your export function have mistake `arrow function` and must something like this

`export initComponent(Moon) => { }` let's miss this mistake

You did not understand my problem correctly if you downloaded [this](https://github.com/kbrsh/moon/files/2093749/MoonIssue.zip) file

It does not take much time because it does not contain a lot of files

as I said, two more steps 1-`npm install` then `npm run dev` for understanding this nonsense problem

**Comment by kbrsh** [comment]
Ahh I switched between the syntax haha.

Your codepen doesn't work because the child component is still being registered incorrectly. You need to import both child and parent component initialize functions in `app.js`.

**Comment by riiccardo** [comment]
i think i have to solve problem by my self and look vuejs issue 🚶

**Comment by kbrsh** [comment]
I gave you a solution. It's your job to apply it — I'm not here to write _your_ code, but am willing to help.

**Comment by riiccardo** [comment]
solution for m-for issue:

`global.Moon = require("moonjs")`

`m-literal:NameOfArray="NameOfArray"`


`and Props`
