### ISSUE TITLE
Parcel unable to build on Windows

### ISSUE THREAD

**Issue by jutxle** [kbrsh/moon#232]
OS: Windows 10

Issue: Path separators are being lost, resulting in unresolveable filenames

![image](https://user-images.githubusercontent.com/7784312/43207920-27fecfca-8ff7-11e8-8801-5fd25eab0da6.png)

**Comment by kbrsh** [comment]
[Moon v1 beta 3 is out](https://kbrsh.github.io/moon), and it uses Webpack and a new compiler. Let me know if it works.

**Comment by kbrsh** [comment]
Moon now does not resolve any paths on its own, so this shouldn't be an issue.
