### ISSUE TITLE
moon-cli error while creating project

### ISSUE THREAD

**Issue by macelocosta** [kbrsh/moon#234]
OS: Win10
Error: when I try to create a new project using moon-cli, it throws the following error:

```
λ moon my-app
download template
C:\Users\Mac\AppData\Roaming\npm\node_modules\moon-cli\index.js:43
                if (err) throw err;
                         ^

Error: Command failed: mkdir C:\Development\my-app; tar -xzf C:\Users\Mac\AppData\Roaming\npm\node_modules\moon-cli\moon-template.tar.gz -C C:\Development\my-app --strip=1
J� existe uma subpasta ou um arquivo C:\Users\Mac\AppData\Roaming\npm\node_modules\moon-cli\moon-template.tar.gz.
Erro ao processar: C:\Users\Mac\AppData\Roaming\npm\node_modules\moon-cli\moon-template.tar.gz.
J� existe uma subpasta ou um arquivo C:\Development\my-app.
Erro ao processar: C:\Development\my-app.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

Inside the directory where I call it, some empty folders are created, as the image below shows.
![captura de tela 1](https://user-images.githubusercontent.com/22543290/43287564-ce06bd2e-90fb-11e8-8c0d-7fa289f92cd0.png)
moon-cli version is 1.0.0-beta.1 and Node version is 8.11.3.

**Comment by kbrsh** [comment]
Looks like making the directory failed and you might not have `tar` installed on your system. Test it out and let me know if it is installed.

**Comment by macelocosta** [comment]
I didn't have `tar` installed, but even after installing it, the same error occurred.

**Comment by kbrsh** [comment]
I think the issue may be the semicolon — once I get back from vacation I’ll look more into it.

**Comment by kbrsh** [comment]
I removed the semicolon a while ago so this should be working now :)
