### ISSUE TITLE
Great Work!

### ISSUE THREAD

**Issue by vitaly-t** [kbrsh/moon#235]
This is a very interesting solution, though I feel robbed - it promised a 3Kb after compression, and it's actually whole 8kb :smile:

I found this library while having started on [my own](https://github.com/vitaly-t/excellent) version of a mini-DOM framework. No worries, it  is very different from what you do here , I'm just looking to steal some ideas for running tests :smile:

**Comment by kbrsh** [comment]
Thanks! It’s actually 3kb minified and gzipped. I’m still working on tests for the beta since there are still a couple of changes I need to make.

**Comment by vitaly-t** [comment]
I know, I was just joking :) I'm working hard on my framework too, only I got stuck trying with automated tests, trying to find a good way to test DOM modifications. Tests sometimes can be a real bummer.

**Comment by vitaly-t** [comment]
It would be nice to share some experience writing things like that ;) Just so, once again, yours is a mini UI framework, while mine is a mini DOM manipulator, so quite different things ;)

By any chance did you come across any issues exporting the library's root interface? You did you use the current approach from the beginning? I'm using the stupid `window` for now, which has issues in the IE, and wonder what should a better way...

**Comment by vitaly-t** [comment]
Thank you for the suggestions! :smile: I'm not sure if I will use roll-up yet, since my library is even smaller than yours, and currently sits in just one single file.

And I was able to sort out the IE-related issues related to global variables. I founf out the hard way that if you include a script as `<script src="../src">`, only IE failed to load the default `index.js`, it requires the full `<script src="../src/index.js">`, dumb browser! :smile:

**Comment by kbrsh** [comment]
Haha IE can be a hassle ;)

Let's continue this discussion over email (available on [my site](https://kabir.sh)) as I don't want to use issues for discussions like these.

**Comment by vitaly-t** [comment]
@kbrsh Yep, thank you! I have also added [chat](https://gitter.im/vitaly-t/excellent) to [the project](https://github.com/vitaly-t/excellent), I appreciate if you offer an opinion and/or help with anything. Cheers!
