### ISSUE TITLE
Component Syntax for "For" does not work

### ISSUE THREAD

**Issue by Rukenshia** [kbrsh/moon#241]
Hi,

just found out that the syntax described in the docs does not work:

```
<For={$item,$index in items}>
    <p>{$item}</p>
    <p>{$index}</p>
</For>

Moon({
    root: "#root",
    items: ["foo", "bar", "baz"]
});
```

results in:
![image](https://user-images.githubusercontent.com/1899599/47952696-a3f86c00-df73-11e8-8134-07b13e849ccf.png)

**Comment by kbrsh** [comment]
Not sure what is causing this issue. I'll look into it and am planning to update the alternate syntax for `<For>`.

**Comment by w33zy** [comment]
I have just started using Moon I am also getting this error...

**Comment by kbrsh** [comment]
This now works with the rewrite:

```js
Moon({
	root: "#root",
	items: ["foo", "bar", "baz"],
	view: `
		<for={$item, $index} of={items}>
			<p>{$item} {$index}</p>
		</for>
	`
});
```
