### ISSUE TITLE
 Is the project active?

### ISSUE THREAD

**Issue by riiccardo** [kbrsh/moon#244]
hey @kbrsh , i still waiting for newer version of moon

and stable moon-cli too coz still does not work

in newer version pls turn back v0.11.0 syntax :))

 for :
1- `Separating sections of each other like ⬇️ `
2- `methods`
3- `hooks`
4- `data object`
5- `Most importantly, it looks like vuejs`

In the new version, everything is done in one section 🤕 

can we have version 0.11.0 documentation ?

Thanks Regards

**Comment by kbrsh** [comment]
Hey @riiccardo!

I had finals week and was busy with school work for a while. Fortunately, they went well and I have time to work on Moon now!

I am happy with the direction Moon is going in, and I think that it is much simpler without the different sections. It unifies all of the various types and makes a Moon instance more flexible and intuitive.

Moon will be different from Vue and the goal is no longer to be a smaller version of it. The new API is simpler and much more flexible.

Thank you all for your feedback. Moon v1 will be picking up in development soon!

**Comment by kbrsh** [comment]
Closing now because development has picked up and new betas and RCs should be released soon! The v1 roadmap (#250) is open for discussion and feedback.
