### ISSUE TITLE
Import libraries to use in components

### ISSUE THREAD

**Issue by Lomomn** [kbrsh/moon#246]
How should I be importing libraries for use in components?  

I am using the default template provided by Moon-CLI, but I have no idea how to import and use axios. 

Sidenote: it's hard to find answers to questions on the issues page because a lot of the syntax has changed since the question was asked. Is there an api doc somewhere that I don't know about with information on every available function that Moon provides?

**Comment by kbrsh** [comment]
Libraries can be used in components by installing them and then using `import` syntax — this works just like it does in JavaScript and can be used to import files and libraries.

```js
import axios from "axios";
```

Thanks for the feedback. There is no API doc but everything should be covered in the documentation, and I'll likely make one when I've finalized the API.

**Comment by Lomomn** [comment]
If I import axios in index.js, I cannot access it in Index.mvl. I get an axios is not defined error. Do I need to use Moon.extend? I have tried `Moon.extend('axios', axios)`, but that returns the same error.

**Comment by kbrsh** [comment]
Sorry if I didn't make it clear. `Moon.extend` is for creating components. Inside of an `mvl` file you can have a `<script>` tag with relevant component options. You can use `import` inside to access libraries and files.

```html
<script>
    import axios from "axios";
</script>
```

**Comment by Lomomn** [comment]
```<h1>{content}</h1>
<button @click={updateContent($event)}>hihi</button>

<style>
h1 {
	font-size: 50px;
	font-weight: 300;
	font-family: -apple-system, BlinkMacSystemFont, Avenir, "Avenir Next", "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;
}
</style>

<script>
import axios from "axios";
export default {
	content: "Moon",
	
	updateContent(){
		axios.get('/api').then(res => {
			console.log(res.body.message)
			this.update('content', res.body.message);
		});
	}
}
</script>
```
Gives me the error 
` /frontend/js/components/Index.mvl:12:0: 'import' and 'export' may only appear at the top level (12:0)`

**Comment by Lomomn** [comment]
I'm assuming this is an issue with Parcel, so I guess I'll look into that

**Comment by kbrsh** [comment]
Ahh I see. It's not an issue with Parcel. The MVL compiler puts the `import` inside of a function. This behavior has been fixed in the last few commits, and I'm hoping to release a new beta soon. For now, I'd suggest using a global variable for `axios`.

You can create a `.babelrc` in the root directory and create something like:

```js
{
  "plugins": [
    [
      "import-globals",
      {
        "axios": "axios"
      }
    ]
  ]
}
```

Let me know if that works.

**Comment by Lomomn** [comment]
I created the .babelrc but I still get the same error.

**Comment by kbrsh** [comment]
You can remove the import statement from the component, because the `import-globals` plugin should import it automatically into every file. I think the browser error is because Parcel isn't using its' default Babel configuration. Try adding the following to the `.babelrc`:

```diff
{
+ "presets": [
+   "@babel/env" 
+],
  "plugins": [
    [
      "import-globals",
      {
        "axios": "axios"
      }
    ]
  ]
}
```

**Comment by Lomomn** [comment]
That works! Thanks :)
