### ISSUE TITLE
Just trying example - syntax error

### ISSUE THREAD

**Issue by nottledim** [kbrsh/moon#271]
Using minimal snippet from example:
```
 <html> 
 <body>
     <div id="root"></div>
 </body>
 <script src="https://unpkg.com/moon"></script>
 <script src="https://unpkg.com/moon-browser"></script>
 <!-- As an inline script -->
 <script type="text/moon">
    <!-- Sets view and data drivers -->
    Moon.use({
        data: Moon.data.driver,
        view: Moon.view.driver("#root")
    })
    <!-- Runs the app -->
    Moon.run(() => {
        data: [],
        view: <viewTodos data=[]>
    })
 </script>
  </html>
```
Results in:
```
Uncaught SyntaxError: Unexpected token ':'
    at t (moon-browser.min.js:7)
    at HTMLDocument.<anonymous> (moon-browser.min.js:7)
```

**Comment by HaxSam** [comment]
Hey you forgot to define viewTodos

```
const viewTodos = ({ data }) => 
  <ul children=(data.todos.map(todo => 
    <li>{todo}</li> 
  ))/>;
```

Also you have to say witch elements do you want to use with

```
const { ul, li } = Moon.view.m
```

But for the next time rtfm

**Comment by nottledim** [comment]
Yes, but I still get a syntax error with the full code (or your additions).  

> 
But for the next time rtfm

I'm trying

Thanks for your help.

**Comment by kbrsh** [comment]
In Moon, self closing tags must be specified with a closing `/>`. Also, arrow functions need parentheses around the return value if it's an object (this is a JS syntax thing, not moon).

Try this:

```js
Moon.use({
   data: Moon.data.driver,
   view: Moon.view.driver("#root")
});

Moon.run(() => ({
   data: [],
   view: <viewTodos data=[]/>
}));
```

**Comment by nottledim** [comment]
It probably was that closing tag, I didn't see that.  It was code copied from a example in a blog.  When I replaced it with the similar code on the moon website it worked.   I misread the browser error message as an error with the library ;-)  Live and learn. 
I'm sorry to have wasted your time.

**Comment by kbrsh** [comment]
@nottledim Don't worry about it! It took me a while to see the error too, the object return syntax always gets me. As for Moon, better syntax errors are coming in the next beta. Hope you enjoyed trying it out! :)
