### ISSUE TITLE
More Examples for Moon

### ISSUE THREAD

**Issue by adekoyejoakinhanmi** [kbrsh/moon#54]
Are there more examples coming in order to illustrate what can be done with Moonjs?

**Comment by KingPixil** [comment]
I'd love to add more examples! Do you have any specific examples you'd like me to make?

**Comment by adekoyejoakinhanmi** [comment]
I think an example that consumes an external API would be good. I could make it and send in a PR asap. Tell me what you think.

**Comment by KingPixil** [comment]
Sure! Does a Github commit display sound good? It'll basically display a list of the latest commits from this repository.

For styling, use [Wing](http://usewing.ml), and for Moon, use the version in the `dist` directory of the `gh-pages` branch. Just copy another example and edit the code, and if you'd like, I can handle the styling.

**Comment by adekoyejoakinhanmi** [comment]
That's fine, I'll do just that. Please give me between 24-36 hrs. It's a public holiday where I live.

**Comment by KingPixil** [comment]
No problem, thanks for helping out.

**Comment by nam-co** [comment]
Hi, thanks for the work in moon, how about an example of a foreach list with filters (checkboxes, radios, text search and sorting) or using jquery getjson inside moon... anyway thank you

**Comment by KingPixil** [comment]
@nam-co Sure! Just to clarify, you'd like an app that has special options to sort through a list?

**Comment by adekoyejoakinhanmi** [comment]
Hey @KingPixil Do you mind if I build this as well

**Comment by KingPixil** [comment]
@adekoyejoakinhanmi Don't mind at all! Thanks for helping out.

**Comment by adekoyejoakinhanmi** [comment]
@KingPixil Alright then, thanks. @nam-co do you have a sample data or app in mind?

**Comment by nam-co** [comment]
Hi, thanks for the reply, sure let me prepare a file

**Comment by nakome** [comment]
I made a exmple on glitch.me with Moon,Moon router and wing

**Preview:**
[https://moon-route-demo.glitch.me](https://moon-route-demo.glitch.me)

You can Remix & fun :)

**Comment by KingPixil** [comment]
@nakome That looks super cool! I'll add that as an example for Moon Router.

@adekoyejoakinhanmi @nam-co I'm working on a real-time search example with Moon, Wing, and [Wade](https://github.com/KingPixil/wade).

**Comment by adekoyejoakinhanmi** [comment]
@KingPixil I look forward to the example. Does that displace the need to develop a filterable list?
@nam-co You haven't posted the sample data, have you?

**Comment by KingPixil** [comment]
@adekoyejoakinhanmi I think we can just add filter options to the list example. I already have a working version [here](http://moonjs.ga/examples/search.html).

**Comment by KingPixil** [comment]
Do we need any more official examples, or can this be closed?

**Comment by kbrsh** [comment]
I think there are enough examples for now, let me know if you any of you have ideas for more examples!
