### ISSUE TITLE
Conditional classes with hyphens

### ISSUE THREAD

**Issue by kaasasolut** [kbrsh/moon#94]
How can I do something like

    <h1 m-literal:class="{icon: true, 'icon-close': condition}"></h1>

In the current version [(v0.11.0)](https://github.com/kbrsh/moon/releases/tag/v0.11.0) that doesn't work.

[(Vue.js documentation with its solution)](https://vuejs.org/v2/guide/class-and-style.html#Object-Syntax)

Thanks for your work so far.

**Comment by kbrsh** [comment]
It seems to be working, can you provide a jsFiddle reproducing the issue?

**Comment by kaasasolut** [comment]
It was a mistake on my side. Sorry that I bothered you.
My code created something like

    <h1 m-literal:class="{icon: true, &quot;icon-close&quot;: condition}"></h1>

instead of

    <h1 m-literal:class="{icon: true, 'icon-close': condition}"></h1>

I just found it out while preparing the JSFiddle.
