### ISSUE TITLE
IE9 bug: literal:class has trouble

### ISSUE THREAD

**Issue by kaasasolut** [kbrsh/moon#96]
Hello. This time I'm prepared with [a Fiddle](https://jsfiddle.net/MrYeah/8b2vusea/2/). 😉

The evaluation of `literal:class` fails on some circumstances in IE9. It works well on IE11 (didn't test IE10) and other browsers.

You may have to [run it as a draft](http://doc.jsfiddle.net/basic/introduction.html#draft-page) in order to test it on IE9.

**Comment by kaasasolut** [comment]
There are no errors.

The expected generated HTML code of the fiddle is

    <table class="table">
        <thead>
            <tr>
                <th>Test 1 <span class="glyphicon glyphicon-sort"></span></th>
                <th>Test 2 <span class="glyphicon glyphicon-sort"></span></th>
                <th>Test 3 <span class="glyphicon glyphicon-sort"></span></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>a</td>
                <td>b</td>
                <td>c</td>
            </tr>
        </tbody>
    </table>

but IE9 generates something like

    <table class="">
        <thead>
            <tr>
                <th>Test 1 <span class=""></span></th>
                <th>Test 2 <span class="glyphicon glyphicon-sort"></span></th>
                <th>Test 3 <span class="glyphicon glyphicon-sort"></span></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>a</td>
                <td>b</td>
                <td>c</td>
            </tr>
        </tbody>
    </table>

![Screenshot 1](https://user-images.githubusercontent.com/28891844/29355266-9e91e50e-8270-11e7-8eb6-7d8dca06b856.png)

**But wait! There's more!**

As soon as I press "Edit", the code becomes magically correct.

![Screenshot 2](https://user-images.githubusercontent.com/28891844/29355347-fdba63b2-8270-11e7-9714-8c9296dde49d.png)

And exiting edit mode fixes the bug.

![Screenshot 3](https://user-images.githubusercontent.com/28891844/29355410-3b36fc82-8271-11e7-918f-e213e45f4a27.png)

So, unfortunately, this is a bug you have to experience yourself. You can take one of [the official VMs](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) to test it.

**Comment by kaasasolut** [comment]
I just tested [a similar thing based on Vue.js](https://jsfiddle.net/MrYeah/8b2vusea/3/). That works like intended.

**Comment by kaasasolut** [comment]
Yes!

I found the issue in Vue.js (https://github.com/vuejs/vue/issues/1946) and thus could implement their fix into Moon (https://github.com/kbrsh/moon/pull/97).

**Comment by kbrsh** [comment]
@kaasasolut In v1, you'll be able to do:

```
<span m-literal:className.dom="'glyphicon glyphicon-sort'"></span>
```

Basically, you are telling Moon to put the `className` property on the DOM element itself (hence the `.dom` modifier).

**Comment by kaasasolut** [comment]
That looks very interesting.
However, you should really solve the current issue somehow. Letting it wait until v1 looks amateurish.

The easiest way is to drop the support of IE9 or to document this issue.

**Comment by kbrsh** [comment]
Moon v1 now uses `.className` to set everything, so this issue should be fixed.
