### ISSUE TITLE
Problems with central event handling

### ISSUE THREAD

**Issue by kokujin** [kbrsh/moon#98]
I am trying to update several components from a single, central Moon instance. Here are a few oversimplified snippets to explain what I mean:

The central Moon instance
``````
instance.emit("updated", function(evt) {
  console.log('done')
});
 ``````
The components
 ``````
Moon.component("counter-component", {
  template: `<div>
    <ul m-on:updated="update">
        <li m-for="item in list">{{item}}</li>
    </ul>
  </div>`,
  data: function() {
    return {
      list: []
    }
  },
  methods: {
    update: function() {
      this.set("list", instance.get("instanceList");
    }
  }
});
``````

The custom event never gets executed by the other components
`" <ul m-on:updated="update">"`

Can someone tell me what I am doing wrong? Thanks

**Comment by kbrsh** [comment]
Hey!

Custom events can't be listened to via `m-on`, but only when [initializing a component](http://moonjs.ga/docs/components.html#parent-child-communication). This allows for parent-child communication.

For components to all have a shared state, you can use an event bus, like:

```js
const bus = new Moon();

Moon.component("child", {
  methods: {
    someMethod() {
      bus.emit("updateMsg", {
        msg: "New Message"
      });
    }
  }
});

new Moon({
  data: {
    msg: "Hello Moon!"
  },
  hooks: {
    init() {
      const self = this;
      bus.on("updateMsg", (payload) => {
        self.set("msg", payload.msg);
      });
    }
  }
});
```

You can also use a state manager, [Monx](https://github.com/kbrsh/monx) is the official state manager for Moon.

**Comment by kokujin** [comment]
@kbrsh Great! Monx works as expected. Thanks
