### ISSUE TITLE
Easier component template coding?

### ISSUE THREAD

**Issue by kokujin** [kbrsh/moon#99]
What is the preferred, more comfortable way to create component templates? Could I use something like [hyperscript](https://github.com/hyperhype/hyperscriptl)?

At the moment:
`````
Moon.component('my-component', {
  template: "<p>This is a Component!</p>"
});
`````

or
`````
template: `<div>
    <p>Count: {{count}}</p>
    <button m-on:click="increment">Increment</button>
  </div>`,
`````

Thanks

**Comment by kokujin** [comment]
I just found [HyperMoon](http://moonjs.ga/docs/compiler.html), this is what I should use, correct?

**Comment by kbrsh** [comment]
If you _really_ need more control, you can use HyperMoon, but it isn't documented (yet). It's a very strict version of hyperscript, allowing for the Moon compiler to make optimizations that don't have a cost at runtime when the `m` function needs to normalize the parameters.

The best way to create components is through single file components. Check out `moon-cli` to generate a project using them. Basically, they allow you to have templates like:

```html
<template>
  <h1>Component! Content prop: {{content}}</h1>
</template>
<style scoped>
h1 {
  color: #f1f1f1;
}
</style>
<script>
  exports = {
    props: ["content"]
  }
</script>
```

**Comment by kokujin** [comment]
Nice. But is HyperMoon also usable outside the render function scope? My reason being that I have a build chain and skeleton app that I would like to keep for now. 

HyperMoon usage in core
``````
 render: function(m) {
            return m('h1', { attrs: {} }, { shouldRender: false }, [m("#text", { shouldRender: false }, "Hello Moon!")]);
        }
 ``````

Thanks

**Comment by kbrsh** [comment]
Yes, it is available with `Moon.util.m`.

I can give you a basic rundown of HyperMoon:

* The basic format goes like:
  - Elements - `m("tag", { attrs:{} }, { shouldRender: true }, [/* children */]);`
  - Text - `m("#text", { shouldRender: true }, "Some Content");`
* The `meta` parameter (`{ shouldRender: true }`) decides if Moon will skip over that certain element when diffing. Only set it to `true` if any children have some dynamic property that can be updated.
* To interpolate data, you can do something like `m("#text", { shouldRender: true }, this.get("msg"));`

**Comment by kokujin** [comment]
One problem though, I tried something:

`````
const m = Moon.util.m;

Moon.component("foo-component", {
        template: m('h1', { attrs: {} }, { shouldRender: false }, [m("#text", { shouldRender: false }, "Hello Moon!")])
    });

`````
This causes an error:

`````
Uncaught TypeError: Cannot read property 'type' of undefined
`````

What have I done wrong? Moon.Js is a lot of fun :)

**Comment by kbrsh** [comment]
A template cannot be an output of a function, you need to do something like:

```js
Moon.component("foo-component", {
  render: function(m) {
    return  m('h1', { attrs: {} }, { shouldRender: false }, [m("#text", { shouldRender: false }, "Hello Moon!")]);
  }
});
```js

**Comment by kokujin** [comment]
Nice! Great work you've done on the framework.

**Comment by kbrsh** [comment]
Thank you! Glad I could help.
